### ISSUE TITLE
switch internal api load balancer to SSL

### ISSUE THREAD

**Issue by jaymccon** [aws-quickstart/quickstart-redhat-openshift#100]
Currently the ELB uses a TCP listener for internal connections to port 443, this can cause intermittent `TLS handshake timeout` error when connecting to the APIServer.

Suggested workaround is to switch to a SSL listener, which will require an additional DNS record and ACM certificate to be added.

**Comment by philipakash** [comment]
Looks like this is related : https://github.com/aws-quickstart/quickstart-redhat-openshift/issues/112

Can you please add some more explanation ?

**Comment by jaymccon** [comment]
@philipakash We were seeing an issue where the elb was failing intermittently when oc cli was run from one of the master nodes. This has been addressed by ensuring that when oc is run directly on a master, it calls the local api and does not go through the load balancer.
