### ISSUE TITLE
Startup fails on Ansible ping all in AnsibleConfigServer UserData

### ISSUE THREAD

**Issue by Jisher** [aws-quickstart/quickstart-redhat-openshift#103]
The template startup fails and stalls on the "qs_retry_command 50 ansible -m ping all" command in the AnsibleConfigServer UserData script (~line 88). This causes Ansible not to execute and CloudFormation remains in "CREATE_IN_PROGRESS" status for AnsibleConfigServer resource.

SSH access to the OpenShift nodes is restricted by the ContainerAccessCIDR parameter, which I've set as a trusted IP as per the documentation. The ping fails as it can't reach the nodes via SSH.

**Comment by jaymccon** [comment]
@Jisher thanks for reporting this issue. 

From what I can see it's the RemoteAccessCIDR that allows SSH access to the hosts in the cluster. Additionally all the security groups created include a rule to allow all traffic from hosts in the same vpc.

Are you able to provide any more details on the symptoms you experienced, parameter settings you chose, any errors found in /var/log/ansible.log and what modifications you made to the security group to get it operational. With that I will hopefully be able to reproduce the issue.

**Comment by Jisher** [comment]
Hi @jaymccon thanks for your response.

Here is the overview of instances and security groups up until this issue:

Ansible Config Server
All Traffic - VPC CIDR
SSH - Trusted IP
HTTPS - Trusted IP

ETCD (3 nodes)
All Traffic - VPC CIDR
SSH - Trusted IP
HTTPS - Trusted IP

Master (3 nodes)
All Traffic - VPC CIDR
SSH - Trusted IP
HTTPS - Trusted IP

Nodes (6 nodes)
All Traffic - VPC CIDR
SSH - Trusted IP
HTTPS - Trusted IP

All use OpenShiftSecurityGroup. I'm also unable to SSH to any OpenShift node from the Ansible config server as per point 5 in Step 5 of the deployment guide.

Following repeats in /var/log/ansible.log:

`2018-04-06 10:38:55,461 p=26956 u=root |  ip-xx-x-xx-xxx.eu-west-1.compute.internal | UNREACHABLE! => {
    "changed": false,
    "msg": "SSH Error: data could not be sent to remote host \"ip-xx-x-xx-xxx.eu-west-1.compute.internal\". Make sure this host can be reached over ssh",
    "unreachable": true
}`

Some Parameters:
RemoteAccessCIDR = Trusted IP
ContainerAccessCIDR = Trusted IP (same IP as above)
AnsiblePlaybookType = OpenSource-Version
AnsiblePlaybookGitRepoTag = openshift-ansible-3.7.40-1

`# ansible --version`
`ansible 2.4.2.0`

Still investigating a workaround.

**Comment by jaymccon** [comment]
@Jisher I can't see anything in those sg's that would prevent traffic. Are you launching the quickstart into an existing VPC ? if so, you might want to check that the subnet routes and nacl's allow traffic between the hosts.

**Comment by Jisher** [comment]
Hi @jaymccon this was launching into a new VPC created by the template. We were able to workaround the issue by doing the following:
- Adding the SSH key to the Ansible config server and running commands with "--key-file /path/to/key"
- Changing ansible_ssh_user to ec2-user in /etc/ansible/hosts
- Uncommenting the become settings under privilege_escalation in /etc/ansible/ansible.cfg

Since this, we have been able to complete installation of OpenShift via the CloudFormation and Ansible.

**Comment by jaymccon** [comment]
@Jisher thanks for sharing the steps you followed to get up and running.

It is a bit strange though, as there should be no manual steps required. The template creates and shares an ssh key with the hosts (for root user, so no need for become). If you are running by hand perhaps running the ansible scripts as root will work without needing the extra steps you had to perform.

I'll close this for now, go haead and re-open if you feel there is more action required.
