### ISSUE TITLE
OSE Scaler  : ETCD Scale Up Fails while executing the TASK [Add new etcd members to cluster] 

### ISSUE THREAD

**Issue by philipakash** [aws-quickstart/quickstart-redhat-openshift#109]
I dropped 1/3 ETCD Instance and the ETCD scaler playbook fails.
```
TASK [Add new etcd members to cluster] *******************************************************************************************************************************************************************
FAILED - RETRYING: Add new etcd members to cluster (3 retries left).
FAILED - RETRYING: Add new etcd members to cluster (2 retries left).
FAILED - RETRYING: Add new etcd members to cluster (1 retries left).
fatal: [10.76.10.54 -> 10.76.12.45]: FAILED! => {"attempts": 3, "changed": true, "cmd": ["/usr/bin/etcdctl", "--cert-file", "/etc/etcd/peer.crt", "--key-file", "/etc/etcd/peer.key", "--ca-file", "/etc/etcd/ca.crt", "-C", "https://10.76.12.45:2379", "member", "add", "10.76.10.54", "https://10.76.10.54:2380"], "delta": "0:00:02.041385", "end": "2018-04-07 17:44:36.045616", "failed_when_result": true, "msg": "non-zero return code", "rc": 1, "start": "2018-04-07 17:44:34.004231", "stderr": "client: etcd cluster is unavailable or misconfigured; error #0: client: endpoint https://10.76.10.240:2379 exceeded header timeout\n; error #1: client: etcd member https://10.76.11.112:2379 has no leader\n; error #2: client: etcd member https://10.76.12.45:2379 has no leader", "stderr_lines": ["client: etcd cluster is unavailable or misconfigured; error #0: client: endpoint https://10.76.10.240:2379 exceeded header timeout", "; error #1: client: etcd member https://10.76.11.112:2379 has no leader", "; error #2: client: etcd member https://10.76.12.45:2379 has no leader"], "stdout": "", "stdout_lines": []}

NO MORE HOSTS LEFT ***************************************************************************************************************************************************************************************
	to retry, use: --limit @/usr/share/ansible/openshift-ansible/scaleup_wrapper.retry
```

I am not 100% confident that this is the only solution but this is how I made it work .
I manually removed the deleted ETCD node from the cluster using `etcdctl member remove [member_id]` and then re-ran the playbook and it did a successfully ran the scaler playbook.

Any Thoughts?

**Comment by philipakash** [comment]
I referred this : https://docs.openshift.com/container-platform/3.3/admin_guide/backup_restore.html#backup-restore-adding-etcd-hosts

**Comment by philipakash** [comment]
@agamzn Can you check if this is also a known bug with v1.3?

**Comment by agamzn** [comment]
Attempting to reproduce.

**Comment by philipakash** [comment]
@agamzn Were you able to reproduce the same ?

**Comment by philipakash** [comment]
@agamzn Thanks you so much for the update ... Would writing a playbook to remove ETCD member makes sense?

**Comment by philipakash** [comment]
@agamzn Any estimates ? It would help us to target for prod.

**Comment by jaymccon** [comment]
@philipakash We'd love to assist/facilitate your deployment, feel free to drop me an email if you'd like to get any help preparing for and going into production.

As to estimate timelines @agamzn is actively working on this issue today, so we'll be able to provide a solid ETA shortly.

**Comment by agamzn** [comment]
@philipakash , Apologies for the delay. I have a preliminary playbook that I'm running through the paces right now. It's simple, but it'll do the trick here. One the playbook is verified functional I'll need to make a few minor adjustments to the scaling component to account for this until the upstream playbooks can handle this gracefully. 

For timeline purposes: I anticipate having this in develop, waiting for a merge to master, by EOB 5/23. If something comes up that affects this timeline, I'll let you know. 

Thanks for your patience, I appreciate it!

**Comment by philipakash** [comment]
@jaymccon @agamzn thanks for the update ...

**Comment by agamzn** [comment]
@philipakash This is pending CI (and any adjustments), but the first commit for this is in a482c3671eb14455ce3ded492c5e4acbc7dba3e2

**Comment by agamzn** [comment]
@philipakash after some edits and bugfixes, this is now in master! Resolving. Plz reopen if needed.
