### ISSUE TITLE
an error during deployment

### ISSUE THREAD

**Issue by ssheff** [aws-quickstart/quickstart-redhat-openshift#111]
11:48:22 UTC-0400 | ROLLBACK_IN_PROGRESS | AWS::CloudFormation::Stack | Red-Hat-OpenShift-1 | The following resource(s) failed to create: [OpenShiftStack]. . Rollback requested by user.
-- | -- | -- | -- | --
  | 11:48:22 UTC-0400 | CREATE_FAILED | AWS::CloudFormation::Stack | OpenShiftStack | Requires capabilities : [CAPABILITY_IAM]

**Comment by jaymccon** [comment]
Hi, are you able to provide the events from the "OpenShift" sub-stack, they should provide more detail to point to cause.

**Comment by ssheff** [comment]
11:48:22 UTC-0400 | CREATE_FAILED | AWS::CloudFormation::Stack | OpenShiftStack | Requires capabilities : [CAPABILITY_IAM]
I'm not sure what kind capability_iam trequires though ;-(
can you help to address that issue?

**Comment by ssheff** [comment]
Here is what i'm getting:

15:07:32 UTC-0400 | CREATE_FAILED | AWS::CloudFormation::Stack | Red-Hat-OpenShift-02 | The following resource(s) failed to create: [OpenShiftStack].
-- | -- | -- | -- | --
  | Physical ID:arn:aws:cloudformation:us-east-2:030721560455:stack/Red-Hat-OpenShift-02/a879e7c0-3c28-11e8-bb97-500ab3b9e8f2
  | Client Request Token:Console-CreateStack-4ccf4f2a-525d-4b78-a5ae-17f3db48383b
  | 15:07:31 UTC-0400 | CREATE_FAILED | AWS::CloudFormation::Stack | OpenShiftStack | Requires capabilities : [CAPABILITY_IAM]
  | Client Request Token:Console-CreateStack-4ccf4f2a-525d-4b78-a5ae-17f3db48383b

**Comment by ssheff** [comment]
interesting enough, but it looks like this is persistent problem..... did anyone have the same issue?

**Comment by jaymccon** [comment]
@ssheff the CAPABILITY_IAM is a safeguard for stacks that create IAM resources (which this Quick Start does). If you are using the console you will need to ticket the confirmation checkbox just above the "Create" button on the last page of the stack creation process.

If you are using the cli, you will need to add `--capabilities CAPABILITY_IAM` to the command

I will close this issue, please feel free to re-open if the above does not resolve your issue.

**Comment by ssheff** [comment]
It definitely helped and i was able to progress further. however getting another error:

12:24:06 UTC-0400 | ROLLBACK_COMPLETE | AWS::CloudFormation::Stack | Red-Hat-OpenShift |  
-- | -- | -- | -- | --
  | Physical ID:arn:aws:cloudformation:us-east-2:030721560455:stack/Red-Hat-OpenShift/b4e19150-3e69-11e8-a9f8-503f2f8882d1
  | Client Request Token:Console-CreateStack-aba5dffe-6f7f-4557-87e0-82cb5eb1c1f7
  | 12:24:06 UTC-0400 | DELETE_COMPLETE | AWS::CloudFormation::Stack | VPCStack |  
  | 12:21:49 UTC-0400 | DELETE_IN_PROGRESS | AWS::CloudFormation::Stack | VPCStack |  
  | 12:21:48 UTC-0400 | DELETE_COMPLETE | AWS::CloudFormation::Stack | OpenShiftStack |  
  | 12:16:30 UTC-0400 | DELETE_IN_PROGRESS | AWS::CloudFormation::Stack | OpenShiftStack |  
  | 12:16:25 UTC-0400 | ROLLBACK_IN_PROGRESS | AWS::CloudFormation::Stack | Red-Hat-OpenShift | The following resource(s) failed to create: [OpenShiftStack]. . Rollback requested by user.
  | Physical ID:arn:aws:cloudformation:us-east-2:030721560455:stack/Red-Hat-OpenShift/b4e19150-3e69-11e8-a9f8-503f2f8882d1
  | Client Request Token:Console-CreateStack-aba5dffe-6f7f-4557-87e0-82cb5eb1c1f7
  | 12:16:24 UTC-0400 | CREATE_FAILED | AWS::CloudFormation::Stack | OpenShiftStack | Embedded stack arn:aws:cloudformation:us-east-2:030721560455:stack/Red-Hat-OpenShift-OpenShiftStack-9RTTZT1UC8LK/4ce87b80-3e6a-11e8-aaaa-50faf6dde835 was not successfully created: The following resource(s) failed to create: [OpenShiftNodeASG, OpenShiftEtcdASG, OpenShiftMasterASG].
