### ISSUE TITLE
AutoScale Errors

### ISSUE THREAD

**Issue by waynedovey** [aws-quickstart/quickstart-redhat-openshift#116]
I am seeing the following errors on the aws-ose-qs-scale script. This is the OCP 3.9 version

[root@ip-10-0-143-42 ssm]# /bin/aws-ose-qs-scale
Traceback (most recent call last):
  File "/bin/aws-ose-qs-scale", line 14, in <module>
    sys.exit(main())
  File "/bin/aws-ose-qs-scale", line 11, in main
    return aws_openshift_quickstart.scaler.main()
  File "/usr/lib/python2.7/site-packages/aws_openshift_quickstart/scaler.py", line 308, in main
    ClusterGroups.setup()
  File "/usr/lib/python2.7/site-packages/aws_openshift_quickstart/utils.py", line 646, in setup
    for group in cls._determine_cluster_groups():
  File "/usr/lib/python2.7/site-packages/aws_openshift_quickstart/utils.py", line 658, in _determine_cluster_groups
    _g = LocalASG(all_groups[i])
  File "/usr/lib/python2.7/site-packages/aws_openshift_quickstart/utils.py", line 487, in __init__
    for scaling_event in self._grab_current_scaling_events():
  File "/usr/lib/python2.7/site-packages/aws_openshift_quickstart/utils.py", line 542, in _grab_current_scaling_events
    _se = LocalScalingActivity(scaling_activities[i])
  File "/usr/lib/python2.7/site-packages/aws_openshift_quickstart/utils.py", line 413, in __init__
    self.event_type = self._determine_scale_type()
  File "/usr/lib/python2.7/site-packages/aws_openshift_quickstart/utils.py", line 436, in _determine_scale_type
    self.log.debug("Event description: {}".format(t))
NameError: global name 't' is not defined

Current Hosts file

OSEv3:
  children:
    etcd:
      hosts:
        ip-10-0-16-68.ap-southeast-2.compute.internal:
          instance_id: i-0de7c65216afd6fa0
        ip-10-0-63-62.ap-southeast-2.compute.internal:
          instance_id: i-0b6daced5e36e9584
        ip-10-0-86-254.ap-southeast-2.compute.internal:
          instance_id: i-01ba69f19fd4e5e9c
    masters:
      hosts:
        ip-10-0-0-220.ap-southeast-2.compute.internal: &id001
          instance_id: i-0aca0af2550f90037
          openshift_node_labels:
            region: primary
            zone: default
          openshift_schedulable: 'true'
        ip-10-0-59-190.ap-southeast-2.compute.internal: &id002
          instance_id: i-026fb9eb1923ebdb8
          openshift_node_labels:
            region: primary
            zone: default
          openshift_schedulable: 'true'
        ip-10-0-79-16.ap-southeast-2.compute.internal: &id003
          instance_id: i-05e80e212b4528c7d
          openshift_node_labels:
            region: primary
            zone: default
          openshift_schedulable: 'true'
    new_etcd: {}
    new_masters: {}
    new_nodes: {}
    nodes:
      hosts:
        ip-10-0-0-220.ap-southeast-2.compute.internal: *id001
        ip-10-0-26-101.ap-southeast-2.compute.internal:
          instance_id: i-00fa43f5e9def07c2
          openshift_node_labels:
            application_node: 'yes'
            region: infra
            registry_node: 'yes'
            router_node: 'yes'
            zone: default
        ip-10-0-48-167.ap-southeast-2.compute.internal:
          instance_id: i-0ad13d5464490fcb1
          openshift_node_labels:
            application_node: 'yes'
            region: infra
            registry_node: 'yes'
            router_node: 'yes'
            zone: default
        ip-10-0-59-190.ap-southeast-2.compute.internal: *id002
        ip-10-0-75-36.ap-southeast-2.compute.internal:
          instance_id: i-0273f42380cc352f5
          openshift_node_labels:
            application_node: 'yes'
            region: infra
            registry_node: 'yes'
            router_node: 'yes'
            zone: default
        ip-10-0-79-16.ap-southeast-2.compute.internal: *id003
    provision_in_progress: {}
  vars:
    ansible_ssh_user: root
    containerized: 'false'
    openshift_clock_enabled: 'true'
    openshift_cloudprovider_kind: aws
    openshift_clusterid: owned
    openshift_deployment_type: openshift-enterprise
    openshift_master_api_port: '443'
    openshift_master_cluster_hostname: Red-H-OpenS-2S94DQ37MHQR-802afcafbf8f950c.elb.ap-southeast-2.amazonaws.com
    openshift_master_cluster_method: native
    openshift_master_cluster_public_hostname: openshift.aws.megatron.world
    openshift_master_console_port: '443'
    openshift_master_default_subdomain: openshift.aws.megatron.world
    openshift_master_identity_providers: '[{''name'': ''htpasswd_auth'', ''login'':
      ''true'', ''challenge'': ''true'', ''kind'': ''HTPasswdPasswordIdentityProvider'',
      ''filename'': ''/etc/origin/master/htpasswd''}]'
    openshift_metrics_cassandra_storage_type: dynamic
    openshift_metrics_hawkular_hostname: metrics.openshift.aws.megatron.world
    openshift_metrics_install_metrics: 'true'
    openshift_metrics_start_cluster: 'true'
    openshift_registry_selector: registry_node=yes
    openshift_router_selector: router_node=yes
    openshift_web_console_prefix: openshift3/ose-
    openshift_web_console_version: v3.9
    osm_default_node_selector: application_node=yes

**Comment by agamzn** [comment]
Thanks @waynedovey , we caught this late yesterday. I'm iterating through now and will have commits shortly.

**Comment by agamzn** [comment]
Looks like Jay addressed this in https://github.com/aws-quickstart/quickstart-redhat-openshift/commit/cfefa7df944314ebab1626b7d00063167a13f463
