### ISSUE TITLE
enhacement - install AWS SSM Agent (and associated policies) during EC2 instance launces 

### ISSUE THREAD

**Issue by dougtoppin** [aws-quickstart/quickstart-redhat-openshift#12]
Installing the AWS SSM Agent on each EC2 instance (and adding the relevant policies) makes it much easier to administer a fleet of instances. Since the Quick Start launches 10 instances it would make post launch configuration and management in general easier to do via SSM Run Command.

**Comment by ngerasimatos** [comment]
I think this should be an option, either enabled or disabled. Some customers will not want the SSM Agent running on their VMs.

**Comment by avattathil** [comment]
I agree with making it an option

**Comment by jaymccon** [comment]
We can no longer make this optional, as part of the updates to implement autoscaling require ssm https://github.com/aws-quickstart/quickstart-redhat-openshift/blob/develop/templates/openshift.template#L2381-L2399

**Comment by jaymccon** [comment]
ssm agent installed and provided required iam permissions: https://github.com/aws-quickstart/quickstart-redhat-openshift/commit/a786c9a685d3d470a094fae067e4468d50c7da38
