### ISSUE TITLE
ACMCErtificateEMail failed to be created

### ISSUE THREAD

**Issue by k1m0n3** [aws-quickstart/quickstart-redhat-openshift#122]
Hello,

I got a creation failed when running the template :
ACMCertificateEmail - Certificate was in failed status 
![image](https://user-images.githubusercontent.com/3524531/39003263-cbfd578e-43fa-11e8-913d-fcf9c89b4f6a.png)

Any idea please ?

Thanks in advance,

**Comment by Dhariaj** [comment]
I had that issue when I was not able to accept the request for the certificate on time.

**Comment by k1m0n3** [comment]
what did you solv it ?

**Comment by k1m0n3** [comment]
What am i supposed to put in the domain name, a public domain purshased from route53 or a simple local domain ?

Thanks.

**Comment by jaymccon** [comment]
Another approach is to use a domain that is hosted with Amazon Route 53. Create a subdomain (hosted zone) off that domain, for example openshift.mydomain.com. Then provide the HostedZoneId and DomainName when launching the stack. If you do this domain validation will be done automatically for you without needing to do an email validation.

For some guidance on how to create a subdomain have a look at this knowledgebase article https://aws.amazon.com/premiumsupport/knowledge-center/create-subdomain-route-53/.
