### ISSUE TITLE
ParameterKey=OpenShiftAdminPassword,ParameterValue=****** doesn't seem to work

### ISSUE THREAD

**Issue by bentterp** [aws-quickstart/quickstart-redhat-openshift#124]
/etc/origin/master/htpasswd is empty after the install finishes and of course, login doesn't work

Adding entries to /etc/origin/master/htpasswd manually on all 3 master nodes mean I can login.

**Comment by zopechetan** [comment]
Same issue for me as well.
@bentterp  Can you tell what entry needs to be added in htpasswd ?

**Comment by bentterp** [comment]
@zopechetan Just use htpasswd to add the admin user to the /etc/origin/master/htpasswd file on all 3 master nodes.
