### ISSUE TITLE
Ansible Bastion should come up earlier

### ISSUE THREAD

**Issue by mandibuswell** [aws-quickstart/quickstart-redhat-openshift#127]
because the Ansible host is one of the last to be set up, if the stack fails before this then it is difficult to get access to the remaining hosts to allow troubleshooting. 
right now the only way is to create another ec2 instance on the same VPC. Would it be possible to create the Ansible bastion first - even if it is just as a jump host to be used in case of failures? Ansible itself could be install last if necessary.

**Comment by robfrut135** [comment]
@mandibuswell +1
I couldn't agree more with that. I had multiple errors deploying the templates, and by default, you don't have way to access the vms
