### ISSUE TITLE
enhancement - forward server logs to cloudwatch

### ISSUE THREAD

**Issue by dougtoppin** [aws-quickstart/quickstart-redhat-openshift#13]
It would facilitate trouble shooting if all of the .server logs were sent to a cloudwatch log group.

Those might include the following:

/var/log/messages
/var/logcloud-init.log
/var/log/choose_repo.log

I am not sure if all of those are relevant or if there are other logs that might be helpful to include.

**Comment by ngerasimatos** [comment]
Good point, we should forward all logging to cloudwatch.

**Comment by avattathil** [comment]
Due to the fact that RHEL subscription passwords and other sensitive infomation are in the logs.  We are not implementing this change.
