### ISSUE TITLE
Error when creating public service: Could not find any suitable subnets for creating the ELB

### ISSUE THREAD

**Issue by bczoma** [aws-quickstart/quickstart-redhat-openshift#138]
On an OpenShift 3.7 platform with default parameters - only DomainName and HostedZoneID provided, I was trying to deploy a publicly accessible service but got following reported:

```
oc describe svc
...
service-controller                      Warning         CreatingLoadBalancerFailed      Error creating load balancer (will retry): Failed to create load balancer for service xxxx: could not find any suitable subnets for creating the ELB
...
```

This has been discussed at many places, including https://github.com/kubernetes/kubernetes/issues/29298 and  https://access.redhat.com/solutions/3346301

In my case, contrary to above knowledge base link, I needed a public ELB, not an internal one.

I ended up resolving that by adding following tags to each of the three public subnets (for each AZs) of the VPC as follows:

```
kubernetes.io/cluster/Red-Hat-OpenShift-OpenShiftStack-xxxxx | owned
kubernetes.io/role/elb |  
```

It would be of great help if CloudFormation could take care of this for a new VPC. Is that possible?

**Comment by jaymccon** [comment]
@bczoma thanks for raising this. 9556eaff857990aa888ca6f2e550fa63028cf554 should address this for both private and public elb's. 

Once CI has completed it's tests the S3 bucket hosting the quickstart templates will be updated and this issue closed, feel free to re-open if the change doesn't correctly address your issue.
