### ISSUE TITLE
proxy support

### ISSUE THREAD

**Issue by pierreozoux** [aws-quickstart/quickstart-redhat-openshift#144]
I saw on AWS announcement and RedHat blog that 3.9 version of this quickstart brings proxy support. I read all the repo but didnt see reference to it.

How is the proxy support enabled? If not implemented yet, what is the plan around and the estimated timeline?

Thanks!

**Comment by jaymccon** [comment]
The configuration hooks are still to be added, likely this will only be supported for existing VPC's (that is the quickstart won't build out a vpc with a proxy)

**Comment by jaymccon** [comment]
pretty sure this is addressed by BYO-AMI support
