### ISSUE TITLE
immutable AMIs?

### ISSUE THREAD

**Issue by pierreozoux** [aws-quickstart/quickstart-redhat-openshift#145]
Is there a plan of having immutable images?

I find it really convenient for install, scaling and updates, it is really fast.

I used kops in the past, and this was really nice compared to the ansible provisionjng that is slow.

Is it the plan with the CoreOS acquisition?

It is just a general question, trying to get a sense of what the future looks like in OpenShift world. Feel free to.close and direct me.to more appropriate channel.

**Comment by jaymccon** [comment]
While baking as much as possible into the ami can provide some benefits, the quick start program generally prefers to bootstrapping instances at launch, which provides more flexibility and has a lower maintenance footprint.
