### ISSUE TITLE
Upgrade the project to support 3.10

### ISSUE THREAD

**Issue by pierreozoux** [aws-quickstart/quickstart-redhat-openshift#152]

**Comment by jaymccon** [comment]
Work is beginning on this, I hope to have something ready to test shortly

**Comment by pierreozoux** [comment]
I was thinking to start working on this too, then tell me once you have anything to test. I'll work on other things in parallel.

**Comment by jaymccon** [comment]
Thanks @pierreozoux 😄 

branch for the 3.10 release is [here](https://github.com/aws-quickstart/quickstart-redhat-openshift/tree/release-v3.10). initial commits are in, but still needs testing.

**Comment by pierreozoux** [comment]
Tested on my side, and works as expected.
(Just tested `oc get po` and `oc get no`)

As mentionned in #162 I don't use github for the ansible playbooks, so I had to add `openshift-ansible` to the `yum install` command.
And the service catalog fails for now in my enterprise env, so I had to:
```
openshift_enable_service_catalog: false
```

But besides these 2 that are specific to my env, everything looks perfect :)

Congratz 🎉
