### ISSUE TITLE
Add support for pre/post hooks.

### ISSUE THREAD

**Issue by pierreozoux** [aws-quickstart/quickstart-redhat-openshift#159]

**Comment by pierreozoux** [comment]
What do you think about this logic for bash hooks:

```
if [ -f /usr/var/lib/quickstart/pre-install.sh ]
then
  /usr/var/lib/quickstart/pre-install.sh
fi
```

Then If I provide an AMI with these scripts, they get executed at the beginning or at the end of the bootstrap.

**Comment by jaymccon** [comment]
that looks good to me, only change that I would consider (not a blocker in my view) is if it's a good idea to have a generic path `/quickstart/` or do something more specific `/openshift-quickstart/`.
