### ISSUE TITLE
Question: why using ansible playbook from github?

### ISSUE THREAD

**Issue by pierreozoux** [aws-quickstart/quickstart-redhat-openshift#162]
In the enterprise version of OpenShift, the playbooks come from RPM.
And this is the main difference between OCP install and origin.

In my enterprise environment, I don't have access to github, and this part fails.
For now I commented the code, and it works just fine.

I'm wondering if there is a specific reason to use the git version instead of the RPM one?

If there is non, then, we can remove this logic.

If there is, we could make the ansible repo a submodule, that gets uploaded as a bundle of the quickstart, what do you think about this idea?

**Comment by jaymccon** [comment]
Originally we used the RPM, then when the quickstart was rendered non-functional by issues with it we added the option to use the github upstream, as a workaround, and eventually removed the rpm altogether as we could see no value in offering it over the github builds which have a lower latency to getting fixes merged.

I'm not against submoduling the openshift-ansible repo, just wondering what the benefit would be. All I can think of is some stability by having the commit level locked (a double edged sword, as we then have to manage keeping the submodule updated) and perhaps that we can pull the source from the same s3 bucket, so reducing the requirement for internet access (there are still other parts of the quickstart that need egress to the net).

**Comment by pierreozoux** [comment]
It is what I thought, makes sense.

We are already keeping the openshift-ansible repo [here](https://github.com/aws-quickstart/quickstart-redhat-openshift/blob/c79f5e37e33e92702ac5bc812faf5654f13e4a08/templates/openshift.template#L363), so making it a submodule and maintaining that should be the same work.

But I ust asked RedHat, and they don't support openshift-ansible git repo, but only the RPM version.

So, to be a good quickstart, we need the RPM version, but to debug, we need the git version.
Should we put this behind a configuration flag?

**Comment by jaymccon** [comment]
Yep, sounds good. Agree on the submodule and additional parameter, something like "InstallerSource" with possible values of "github" or "rpm"
