### ISSUE TITLE
Issue with RH licensing

### ISSUE THREAD

**Issue by matthiasbuchner** [aws-quickstart/quickstart-redhat-openshift#17]
After relaunching the stack several times trying different settings, I did not realized the "Entitlement Usage" for my Openshift trial license maxed out.

If you were to add
   subscription-manager list --available --matches '*OpenShift*'
in quickstart-redhat-openshift/scripts/redhat_ose-register.sh, before attaching to the pool id, it may make it easier for others to spot this problem.

Thanks for putthing this QS together.

**Comment by avattathil** [comment]
@matthiasbuchner thanks for the suggestion I am adding this to the next release milestone

**Comment by ngerasimatos** [comment]
Excellent suggestion.

**Comment by shadycuz** [comment]
@avattathil Also I don't think you can have your password start with `$`

**Comment by avattathil** [comment]
Updated in https://github.com/aws-quickstart/quickstart-redhat-openshift/commit/7dd91792d2ca0ca87866acb9c9c92843c46d0357
