### ISSUE TITLE
Proxy support

### ISSUE THREAD

**Issue by pierreozoux** [aws-quickstart/quickstart-redhat-openshift#174]
now that I can use my own AMI with the QS, I prepare my ami with various proxy settings, and others, and all is good.

I still have an issue, and to be honest, I don't know how to solve it.

`yum` is configured to use my proxy.  but for obvious reasons, [this](https://github.com/aws-quickstart/quickstart-redhat-openshift/blob/master/scripts/ansibleconfigserver_bootstrap.sh#L55) is failing:
```
yum install -y https://s3-us-west-1.amazonaws.com/amazon-ssm-us-west-1/latest/linux_amd64/amazon-ssm-agent.rpm
```

My proxy doesn't allow `amazonaws.com`, and I shouldn't need to go though proxy for that as it is internal.
But yum doesn't know about the `NO_PROXY` env var...

I'm currently using this [workaround](https://github.com/pierreozoux/quickstart-redhat-openshift/commit/d3dbe23e85bbf227667b4c6ad6aa5ab629be8b56), but I can't PR this to this repo.

How could we make it work with the upstream quickstart for me and others?

Thanks for your help!

**Comment by jaymccon** [comment]
would something like:

```bash
export PROXY='' wget https://s3-us-west-1.amazonaws.com/amazon-ssm-us-west-1/latest/linux_amd64/amazon-ssm-agent.rpm
yum install -y ./amazon-ssm-agent.rpm
```

In the longer term I would like to see having private subnets with a proxy supported in the VPC quickstart, so that we can test against and fully support proxied environments.
