### ISSUE TITLE
public access to application URLs

### ISSUE THREAD

**Issue by tobmat** [aws-quickstart/quickstart-redhat-openshift#18]
This is awesome!  The one piece I'm struggling with is how to make the application URL's that are generated publicly available.  Any insight or direction would be awesome.  The redhat documentation is confusing to me.

**Comment by Valien** [comment]
@tobmat - are you seeing the svc.local routes when you create a public URL? I'm having a similar issue. Changed my routing config to my subdomain and pointed my DNS to the ELB but accessing applications on 80 or 8080 are timing out as well.

**Comment by ngerasimatos** [comment]
A route is a way to expose a service by giving it an externally-reachable hostname like www.blahblah.com. A defined route and the endpoints identified by its service can be consumed by a router to provide named connectivity that allows external clients to reach your applications. Each route consists of a route name, service selector, and (optionally) security configuration. When you assign a service a route the service should be accessible publicly. 

https://docs.openshift.com/enterprise/3.0/architecture/core_concepts/routes.html

If you cannot resolve a route I would check networking security configurations.

**Comment by avattathil** [comment]
thanks @ngerasimatos

**Comment by tobmat** [comment]
So I opened a ticket with Redhat to try and figure this out.  They were a little confused by the configuration.  The public elb points to the master instances but the routers are located on the node instances.  How do I access the node instances from the outside?  They said they usually see the routers located on the master instances.  I added a wildcard DNS entry in route53 pointing to the nodes and that allowed me to curl an application url from the master node.  It resolves from the outside now but I can't access.

**Comment by grastogi78** [comment]
I'm facing the same issue and have been pretty puzzled by the same. I may not be making much sense here but I thought odd that the nodes are sitting behind a non internet facing ALB. @tobmat can you share more details on how or what you did, what kind of a record did you create. Is the wild card entry to an actual internet domain? I've been in touch with Tony to see if he could modify the quickstart with a hello-world app accessible from the internet, this would give more details on how to configure the OS cluster and the AWS configurations (including some ports that may need to be opened).

**Comment by avattathil** [comment]
Reopening

**Comment by avattathil** [comment]
The Quickstart use the default in the Ansible playbook which deploys the router on the nodes. I will investigate and see if the playbook supports moving the router to the master. 
Another option would be to put the nodes behind a internet-facing elb.

**Comment by ngerasimatos** [comment]
A typical design would look like the following:

http://red.ht/2hbJoot

This is based on the OCP reference architecture documentation which can be found here:

http://red.ht/2h98rIK

The network is configured to leverage three AWS ELBs for access to the OpenShift API, OpenShift console, and the OpenShift routers. 

The first ELB is for the OpenShift API and console access originating from outside of the cluster. 

The second ELB is for API access within the cluster. 

The third ELB is for accessing services deployed in the cluster that has been exposed through routes. 

DNS is handled by Route53. 

I am not sure of the exact issue that is being stated. If you deploy pods and create services and routes you should be able to access the application.

**Comment by grastogi78** [comment]
@ngerasimatos thanks for the links! from the second link section 3.4 I see that one hosted zone should be present in the AWS console Route 53. Is this created by the Quickstart? I would doubt that since there were no parameters given to that effect. On my cluster I do not see a hosted zone. 

If I dig deeper and want to create a wild card entry ([Link](https://docs.openshift.com/container-platform/3.5/install_config/install/prerequisites.html#wildcard-dns-prereq)) it says "points to the public IP address of the host where the router will be deployed". The Quickstart doesn't create a public IP for the node host or the ELB infront of the node instances. Thoughts. 

>

**Comment by Valien** [comment]
Hey all - good discussion. Here's what I've done with the quickstart. I forked and modified it to fit within my NFR licences from RH (5 systems). And I've been able to stand up a cluster fairly quickly now which is pretty awesome.

By default in the QuickStart only the only internet-facing ELB is the one pointing to the Master on 8443. It says in the documentation (.pdf) that to get external access you would need to add ports and SG rules for the Nodes.

To get my nodes running and available publicly I had to create a new ELB (I copied settings off the existing Master ELB) and added my nodes as the instances there. Been working great for all traffic off 80 with no issues. I also had to change my subdomain URL in the `master-config.yaml` to point to my wildcard FQDN. Once Master was restarted I then (or at same time) created an alias in Route 53 to point to my ELB for the FQDN. 

The QS doesn't provision the nodes for public access by default. Right now I'm trying to get Hawkular running as that is not installed in the QS either (I had to manually install it using the Ansible/OpenShift advance install directions). It's running internally but having some routing issues.

HTH some with those trying to get this up and running. It's a great initial QS but you most likely will need to fork and configure some things post-launch to get it working for your environment.

**Comment by Valien** [comment]
Thanks @ngerasimatos the QS as it is, is a great foundation. So I just forked and modified it for my needs. In regards to external authentication I would definitely look at LDAP and AD related credentials. We're an AD house here so being able to tie into our online AD creds would be pretty awesome.

**Comment by grastogi78** [comment]
after making changes to the master-config.yaml my master controller service isn't coming up. I checked the journalctl -xe and it says something about the definition of the entry for subdomain. I think I'm doing this wrong. @Valien would you be able to share what your entry looks like?
routingconfig:
    subdomain:  *.apps.mydomain.com

I get the below error

`could not load config file "/etc/origin/master/master-config.yaml" due to an error: yaml: line 168: did not find expected alphabetic or numeric character`

**Comment by Valien** [comment]
Hey @grastogi78 - do not put in the wildcard (*) character. Your entry should look similar to this:

`routingConfig:
  subdomain: apps.mydomain.com`

On Route53 just set a wildcard DNS entry that points `*.apps.mydomain.com` to your ELB's public A record and all should work.

Don't forget to do a `systemctl restart atomic-openshift-master.service` so that the config is re-read.

**Comment by sundeepk1** [comment]
@Valien I am unable to get this working .. i have the default quickstart cluster running fine . from there I created an ELB -> post that I am unable to follow . can you please help me with this .

**Comment by sundeepk1** [comment]
@avattathil can you help me with this

**Comment by avattathil** [comment]
@sundeepk1  I am updating the QuickStart to provide an internet-facing ELB. Changes are currently in the develop branch https://github.com/aws-quickstart/quickstart-redhat-openshift/commit/bef7a245bb52e720e11450cd6d75ab45ae052267
Please track the updates in feature-request  https://github.com/aws-quickstart/quickstart-redhat-openshift/issues/21 or watch the repo for updates

**Comment by avattathil** [comment]
Fixed in https://github.com/aws-quickstart/quickstart-redhat-openshift/commit/1efa81e070018199d7df94ad0f9536074542195c
