### ISSUE TITLE
London eu-west-2 region VM AMI ID seems to be out of date

### ISSUE THREAD

**Issue by bczoma** [aws-quickstart/quickstart-redhat-openshift#180]
Getting Template error: Unable to get mapping for AWSAMIRegionMap::eu-west-2::RHEL74HVM

**Comment by bczoma** [comment]
Also getting the same for Paris, eu-west-3

Template error: Unable to get mapping for AWSAMIRegionMap::eu-west-3::RHEL74HVM

**Comment by pierreozoux** [comment]
Do you use master or develop branch?
