### ISSUE TITLE
gluster quick start documentation

### ISSUE THREAD

**Issue by bczoma** [aws-quickstart/quickstart-redhat-openshift#193]
I am trying to get going with using glusterFS on a 3.10 cluster just created and looking for specific documentation of how gluster has been created and deployed by this CloudFormation.

I was looking at e.g. https://docs.openshift.com/container-platform/3.10/install_config/persistent_storage/persistent_storage_glusterfs.html but it is a bit confusing what if anything is already in place and what I'd need to add.

Thank you!

**Comment by bczoma** [comment]
As a user focusing on development rather than storage admin I would expect that after CloudFormation is complete the storage would  be ready for static or dynamic provisioning, as described at https://docs.openshift.com/container-platform/3.10/install_config/persistent_storage/persistent_storage_glusterfs.html#provisioning

However it is unclear what to configure, particularly to 

Define the following PersistentVolume (PV) in gluster-pv.yaml:
...
"The GlusterFS volume that will be accessed."

It seems additional configuration steps are required at the gluster cluster.

**Comment by jaymccon** [comment]
Hi @bczoma 

Only dynamic provisioning is pre-configured at this time, and can be used very simply:

```
$ oc get sc --all-namespaces
NAME                PROVISIONER               AGE
glusterfs-storage   kubernetes.io/glusterfs   7h
gp2 (default)       kubernetes.io/aws-ebs     7h
$ cat << EOF > dynamic.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: claim1
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: glusterfs-storage
  resources:
    requests:
      storage: 30Gi
EOF
$ oc apply -f dynamic.yaml
persistentvolumeclaim/claim1 created
# oc get pvc
NAME      STATUS    VOLUME                        CAPACITY   ACCESS MODES   STORAGECLASS        AGE
claim1    Bound     pvc-aaaa-bbb-ccc-ddd-eeeeee   30Gi       RWX            glusterfs-storage   25s
```

If you need static provisioning, following the doc you linked to is what you'll need to do, or [this](https://docs.openshift.com/container-platform/3.10/install_config/storage_examples/gluster_example.html) example seems to have a little more detail, like that "The GlusterFS volume that will be accessed." need to be pre-created with the gluster or heketi-cli. 

As far as what is done by Cloudformation, there is nothing bespoke, the OpenShift installer does all of the setup for gluster, and is configured in the ansible hosts file [here](https://github.com/aws-quickstart/quickstart-redhat-openshift/blob/master/scripts/predefined_openshift_vars_3.10.txt#L14-L17).

**Comment by bczoma** [comment]
Great, thank you!

**Comment by bczoma** [comment]
Closing this, thanks again.
