### ISSUE TITLE
Scaling up: global name 'ec2' is not defined

### ISSUE THREAD

**Issue by cunei** [aws-quickstart/quickstart-redhat-openshift#196]
We installed a test 3.10 cluster on AWS. When scaling up the number of worker nodes from the "Auto Scaling Group" panel in the EC2 console, a node is created but it never joins the cluster. The messages file on the Ansible server reports:
```
Nov 8 01:56:48 ip-10-0-141-88 amazon-ssm-agent: "output": "making schedulable
setting node group
making schedulable
setting node group
making schedulable
setting node group

----------ERROR-------
Traceback (most recent call last):
 File "/bin/aws-ose-qs-scale", line 17, in <module>
 sys.exit(main())
 File "/bin/aws-ose-qs-scale", line 13, in main
 return aws_openshift_quickstart.scaler.main()
 File "/usr/lib/python2.7/site-packages/aws_openshift_quickstart/scaler.py", line 391, in main
 scale_inventory_groups(ocp_version=args.ocp_version)
 File "/usr/lib/python2.7/site-packages/aws_openshift_quickstart/scaler.py", line 284, in scale_inventory_groups
 _is.process_pipeline()
 File "/usr/lib/python2.7/site-packages/aws_openshift_quickstart/utils.py", line 295, in process_pipeline
 cls.unsubscribe_nodes(cls.nodes_to_remove[category], category)
 File "/usr/lib/python2.7/site-packages/aws_openshift_quickstart/utils.py", line 332, in unsubscribe_nodes
 unsubscribe_url = 'http://subscription.rhn.redhat.com/subscription/consumers/', cls.get_UUID(node_key)
 File "/usr/lib/python2.7/site-packages/aws_openshift_quickstart/utils.py", line 318, in get_UUID
 find_instance = ec2.Instance(nodeID)
NameError: global name 'ec2' is not defined
failed to run commands: exit status 1"
```

**Comment by cunei** [comment]
I applied the pull request #197 to the Ansible server in our cluster; I also found that I needed to change in the `aws_openshift_quickstart/scaler.py` script the line:
```
if category is 'etcd':
```
with
```
if (category is 'etcd') or (category is 'glusterfs'):
```
I also manually edited the `/etc/ansible/script` in order to remove some pending data left by the failing scripts. After that was done, changing the Auto Scaling Group works ok for us, and the new worker nodes duly join the cluster. Thanks!

**Comment by jaymccon** [comment]
@agamzn would you mind to have a quick look at this

**Comment by agamzn** [comment]
The line (+/-) in question:
https://github.com/aws-quickstart/quickstart-redhat-openshift/blob/71f9878b8aa570f290d531141ce7cb0c63b3d7f5/scripts/scaling/aws_openshift_quickstart/scaler.py#L297-L303

`InventoryConfig` relevant lines:
https://github.com/aws-quickstart/quickstart-redhat-openshift/blob/71f9878b8aa570f290d531141ce7cb0c63b3d7f5/scripts/scaling/aws_openshift_quickstart/utils.py#L38-L51

Without the change @cunei mentioned, the scaling actions wont work properly. Currently the categories are transformed from singular to plural (`node` to `nodes`) with the exception of `etcd`. This means `glusterfs`is transformed into `glusterfss`.

I'll submit a PR Monday Morning after I have some :coffee:

**Comment by jaymccon** [comment]
@agamzn 0d52f2c should do it

**Comment by agamzn** [comment]
LGTM;

**Comment by jaymccon** [comment]
closing as it appears this has been addressed in the (merged) PR https://github.com/aws-quickstart/quickstart-redhat-openshift/blob/master/scripts/scaling/aws_openshift_quickstart/utils.py#L318
