### ISSUE TITLE
Cleartext Secrets in Launch Configuration

### ISSUE THREAD

**Issue by irichardson91** [aws-quickstart/quickstart-redhat-openshift#199]
While a cluster created by this quickstart is active, we're able to see redhat user information in cleartext within EC2 > Launch Configurations > User Data rather than this information being encoded in Base64 as we believe was intended. Screenshots attached.
![cae9c396](https://user-images.githubusercontent.com/45039548/48487807-33750900-e817-11e8-8747-b9965a004efc.PNG)
![8b72b29f](https://user-images.githubusercontent.com/45039548/48487806-33750900-e817-11e8-84d7-a6c83b32a5c5.PNG)

**Comment by jaymccon** [comment]
As base64 is trivially decoded, using a SSM ParameterStore SecureString might be the way to go here.

**Comment by pierreozoux** [comment]
Actually internally, we do use ssm to store these params.
Just we get them to feed CF.
Would it make sense to PR to make the QS to get them from ssm?

**Comment by jaymccon** [comment]
I think a switch to ssm is a good fit (now that secure string is supported). I'm working on the update to 3.11 and will try to get this change included.

**Comment by jaymccon** [comment]
@pierreozoux let me know if you're already on it, and I'll focus my efforts on other improvements 😄

**Comment by pierreozoux** [comment]
@ddulek do you have a link to this activation Key?
@jaymccon we already have the update to 3.11, I'll try a PR today

**Comment by ddulek** [comment]
The activation keys are created by the user on the web portal for subscription manager.  A user logs in and creates an activation key.  They can then use that key to register with the satellite server/subscription manager without having to use their username/password.  If using Red Hat account the link to create one is here: https://access.redhat.com/management/activation_keys

In fact, the page will also tell the user the organization number that the user is in.

**Comment by jaymccon** [comment]
@ddulek wouldn't leaking the activation key to logs/uesrdata be undesirable as well ?

**Comment by llegolas** [comment]
It is a band-aid yes.  Whoever can get the activation key will be able to install and register RH server(s) unconditionally. At least the particular user credentials will be safe. But if SSM can be used why not, after all this is what it is meant for right?

**Comment by jaymccon** [comment]
Opted for feeding the existing parameters into Secrets Manager, then the instances fetch values at runtime as needed. Once the ci completes and commit is merged to master branch, this issue will auto-close.
