### ISSUE TITLE
AWS Cloudformation for OKD

### ISSUE THREAD

**Issue by olsib** [aws-quickstart/quickstart-redhat-openshift#206]
Hey guys,

I tried deploying OKD using cloudformation template that you provide, but that does not seem to work.

Does that work wiht OCP only, i.e. we have to have a redhat subscription?

If so is there an alternate way of deploying OKD in AWS, using cloudformation tools?

Thanks,
Olsi

**Comment by pierreozoux** [comment]
Read this issue:
https://github.com/aws-quickstart/quickstart-redhat-openshift/issues/192

@jaymccon I'd close this issue as duplicate, and rename the other one to OKD support.
(Could I get enough rights to GitHub to do this?)
