### ISSUE TITLE
[FAILED] @  Openshift installation failed

### ISSUE THREAD

**Issue by ptrhdk** [aws-quickstart/quickstart-redhat-openshift#208]
Hi,

got stuck with 3.11 OpenShift installation via AWS QuickStart. Can't find any relevant error message in the log .. Any idea ? 

thanks in advance, 

Peter

Dec 09 16:23:46 ip-10-0-141-219.eu-west-1.compute.internal cloud-init[1569]: + ansible-playbook /usr/share/ansible/openshift-ansible/playbooks/prerequisites.yml
Dec 09 16:23:50 ip-10-0-141-219.eu-west-1.compute.internal cloud-init[1569]: [WARNING]: Could not match supplied host pattern, ignoring: oo_lb_to_config
Dec 09 16:23:50 ip-10-0-141-219.eu-west-1.compute.internal cloud-init[1569]: [WARNING]: Could not match supplied host pattern, ignoring: oo_nfs_to_config
Dec 09 16:29:21 ip-10-0-141-219.eu-west-1.compute.internal cloud-init[1569]: + qs_err ' Openshift installation failed, see logs for details '
Dec 09 16:29:21 ip-10-0-141-219.eu-west-1.compute.internal cloud-init[1569]: + touch /var/tmp/stack_failed
Dec 09 16:29:21 ip-10-0-141-219.eu-west-1.compute.internal cloud-init[1569]: + echo '[FAILED] @  Openshift installation failed, see logs for details '
Dec 09 16:29:21 ip-10-0-141-219.eu-west-1.compute.internal cloud-init[1569]: + echo '[FAILED] @  Openshift installation failed, see logs for details '
Dec 09 16:29:21 ip-10-0-141-219.eu-west-1.compute.internal cloud-init[1569]: [FAILED] @  Openshift installation failed, see logs for details
Dec 09 16:29:21 ip-10-0-141-219.eu-west-1.compute.internal cloud-init[1569]: ++ qs_status
Dec 09 16:29:21 ip-10-0-141-219.eu-west-1.compute.internal cloud-init[1569]: ++ '[' -f /var/tmp/stack_failed ']'
Dec 09 16:29:21 ip-10-0-141-219.eu-west-1.compute.internal cloud-init[1569]: ++ printf 1
Dec 09 16:29:21 ip-10-0-141-219.eu-west-1.compute.internal cloud-init[1569]: ++ return 1
Dec 09 16:29:21 ip-10-0-141-219.eu-west-1.compute.internal cloud-init[1569]: + cfn-signal -e 1 --stack Red-Hat-OpenShift-OpenShiftStack-5ZYLEQBTWXT8 --resource AnsibleConfigServer --region eu-west-1
Dec 09 16:29:22 ip-10-0-141-219.eu-west-1.compute.internal cloud-init[1569]: Cloud-init v. 0.7.9 finished at Sun, 09 Dec 2018 16:29:22 +0000. Datasource DataSourceEc2.  Up 850.51 seconds

[cloud_init.txt](https://github.com/aws-quickstart/quickstart-redhat-openshift/files/2660762/cloud_init.txt)

**Comment by ptrhdk** [comment]
[cloud_init.txt](https://github.com/aws-quickstart/quickstart-redhat-openshift/files/2660758/cloud_init.txt)

**Comment by ptrhdk** [comment]
[cloud_init.txt](https://github.com/aws-quickstart/quickstart-redhat-openshift/files/2660760/cloud_init.txt)

**Comment by jaymccon** [comment]
The log you're looking for is `/var/log/ansible.log` on the AnsibleConfigServer
