### ISSUE TITLE
feature request : make ansible configure public access for the cluster

### ISSUE THREAD

**Issue by sundeepk1** [aws-quickstart/quickstart-redhat-openshift#21]
I am facing lots of difficulty to configure public access so that the services are created to be accessible via internet. Currently the services are created with .local extension and i am unable to access them.

**Comment by avattathil** [comment]
@sundeepk1  I have updated the QuickStart and added an external ELB which is attached to the OCP nodes.

Below is a write up of how to expose an application to the public.

### Create a Demo Project 
Chose `Create Project`:

![s3 1](https://user-images.githubusercontent.com/5912128/33403101-e0425bd2-d513-11e7-94b9-7977df42816a.jpg)

Choose `Ruby` form the Catalog:
![s3 2](https://user-images.githubusercontent.com/5912128/33403198-40527ef8-d514-11e7-9eb3-4c38a169396e.jpg)

Keep the default setting click select:
![s3 3](https://user-images.githubusercontent.com/5912128/33403230-5c4ab2b0-d514-11e7-8657-b56fee47ba2f.jpg) 

Provide a value for Name and Git Repo
`Name:`  external-ruby-app
`Branch:` master
`Git Repository URL:`  Click the `Try it` to auto-fill the URL Expand the `advanced options`
![ruby1](https://user-images.githubusercontent.com/5912128/33403393-17915d6c-d515-11e7-87c9-b1b83486f03d.jpg)
Enter the ELB DNS Name in **lowercase**
_Hint: ELB DNS Name is provided in the cloud formation outputs tab under the UI link_

Specfies replicas: `3` 
![ruby3](https://user-images.githubusercontent.com/5912128/33403504-8463928e-d515-11e7-911c-fa9f872df5d3.jpg)

Click `Create`
![ruby4](https://user-images.githubusercontent.com/5912128/33403558-af55348e-d515-11e7-962b-ff28f0cefad0.jpg)

`Go to the Overview `
And monitor progress
![ruby5](https://user-images.githubusercontent.com/5912128/33403590-d186be42-d515-11e7-8ad5-1669b61f9abf.jpg)

When the build is complete screen will update to show `3` pods and build at `100%`
![ruby6](https://user-images.githubusercontent.com/5912128/33403609-e93ace70-d515-11e7-8206-f82cc2feef18.jpg)

Choose the `link` provided to access the application
![ruby7](https://user-images.githubusercontent.com/5912128/33403749-6dfee0a6-d516-11e7-82ba-1abe647eaebd.jpg)

I am finalizing the push and will update this issue once the changes are live in `maste`r and on `s3`

**Comment by avattathil** [comment]
Feature Request complete in https://github.com/aws-quickstart/quickstart-redhat-openshift/commit/c847ebedb5b73374538aa5716598b25ef04d8b64 `master`

ReleaseTag: https://github.com/aws-quickstart/quickstart-redhat-openshift/tree/v1.2

**Comment by avattathil** [comment]
@sundeepk1  Updates are live here: https://aws.amazon.com/quickstart/architecture/openshift/

**Comment by avattathil** [comment]
@sundeepk1  Please re-open if you need further assitance
