### ISSUE TITLE
S3 Bucket not available in Frankfurt/eu-central-1

### ISSUE THREAD

**Issue by kemra102** [aws-quickstart/quickstart-redhat-openshift#22]
It seems that the S3 Bucket containing all the required resources is not available in Frankfurt so running the template in this region fails right now.

Could the required resources be copied to Frankfurt or have the layout of the bucket documented so it can be easily duplicated?

**Comment by avattathil** [comment]
@kemra102 I have added a franfurt support.  
https://s3.eu-central-1.amazonaws.com/quickstart-reference-lambda-eu-central-1/generate_sshkeys/genrsa_lambda.zip

**Comment by kemra102** [comment]
@avattathil Just wanted to confirm is the resources required by Ansible are also added to the bucket? Getting the same issues as described in issue #11 now - wanted to check before I delved too far into debugging the deployment.

**Comment by avattathil** [comment]
Only the lambda assets are region specific. The Ansible config files are
loaded from the production bucket.  Let me know if you need any other
assistance.

Thanks
--Tony

**Comment by avattathil** [comment]
Danny one more item.
Since eu-central-1 did not have support before the AMI mappings also need
to be added.
            "eu-central-1": {
                "RHEL74HVM": "ami-d74be5b8"
            },

I will add this in the next update (just fyi)
Thanks
