### ISSUE TITLE
failed to create: [OpenShiftNodeASG, AnsibleConfigServer, OpenShiftEtcdASG, OpenShiftMasterASG] - redhat_ose-register.sh parse issue?

### ISSUE THREAD

**Issue by matthewmodestino** [aws-quickstart/quickstart-redhat-openshift#224]
Hey Team! 

I am attempting to run the AWS Openshift quickstart and am encountering stack fails with the reason "The following resource(s) failed to create: [OpenShiftNodeASG, AnsibleConfigServer, OpenShiftEtcdASG, OpenShiftMasterASG]."

01 Feb 2019 14:29:15 | Red-Hat-OpenShift-OpenShiftStack-1LNSTE6BH1WIJ | CREATE_FAILED | The following resource(s) failed to create: [OpenShiftNodeASG, AnsibleConfigServer, OpenShiftEtcdASG, OpenShiftMasterASG].
-- | -- | -- | --
01 Feb 2019 14:29:14 | OpenShiftEtcdASG | CREATE_FAILED | Resource creation cancelled
01 Feb 2019 14:29:14 | OpenShiftMasterASG | CREATE_FAILED | Resource creation cancelled
01 Feb 2019 14:29:14 | OpenShiftNodeASG | CREATE_FAILED | Resource creation cancelled
01 Feb 2019 14:29:12 | AnsibleConfigServer | CREATE_FAILED | Received FAILURE signal with UniqueId i-0f98f6372dc555b05

After disabling stack rollback and accessing the `ansible-configserver` and running `journalctl | grep cloud-init`

It looks like the register script is failing with `Feb 01 14:29:11 ip-10-0-136-253.ec2.internal cloud-init[1530]: parse error: Invalid numeric literal at line 1, column 53` ?

```
Feb 01 14:29:10 ip-10-0-136-253.ec2.internal cloud-init[1530]: + /root/redhat_ose-register.sh <REDACTED>
Feb 01 14:29:10 ip-10-0-136-253.ec2.internal cloud-init[1530]: --------------------------------
Feb 01 14:29:10 ip-10-0-136-253.ec2.internal cloud-init[1530]: Available quickstart_functions:
Feb 01 14:29:10 ip-10-0-136-253.ec2.internal cloud-init[1530]: #qs_err
Feb 01 14:29:10 ip-10-0-136-253.ec2.internal cloud-init[1530]: #qs_status
Feb 01 14:29:10 ip-10-0-136-253.ec2.internal cloud-init[1530]: #qs_get-ostype
Feb 01 14:29:10 ip-10-0-136-253.ec2.internal cloud-init[1530]: #qs_get-osversion
Feb 01 14:29:10 ip-10-0-136-253.ec2.internal cloud-init[1530]: #qs_get-python-path
Feb 01 14:29:10 ip-10-0-136-253.ec2.internal cloud-init[1530]: #qs_bootstrap_pip
Feb 01 14:29:10 ip-10-0-136-253.ec2.internal cloud-init[1530]: #qs_update-os
Feb 01 14:29:10 ip-10-0-136-253.ec2.internal cloud-init[1530]: #qs_enable_epel
Feb 01 14:29:10 ip-10-0-136-253.ec2.internal cloud-init[1530]: #qs_notty
Feb 01 14:29:10 ip-10-0-136-253.ec2.internal cloud-init[1530]: #qs_aws-cfn-bootstrap
Feb 01 14:29:10 ip-10-0-136-253.ec2.internal cloud-init[1530]: #qs_cloudwatch_tracklog
Feb 01 14:29:10 ip-10-0-136-253.ec2.internal cloud-init[1530]: #qs_cloudwatch_install
Feb 01 14:29:10 ip-10-0-136-253.ec2.internal cloud-init[1530]: #qs_retry_command
Feb 01 14:29:10 ip-10-0-136-253.ec2.internal cloud-init[1530]: --------------------------------
Feb 01 14:29:10 ip-10-0-136-253.ec2.internal cloud-init[1530]: [INFO] Dependencies Met!
Feb 01 14:29:10 ip-10-0-136-253.ec2.internal cloud-init[1530]: Loaded plugins: amazon-id, rhui-lb, search-disabled-repos
Feb 01 14:29:10 ip-10-0-136-253.ec2.internal cloud-init[1530]: Cleaning repos: epel rhui-REGION-client-config-server-7
Feb 01 14:29:10 ip-10-0-136-253.ec2.internal cloud-init[1530]: : rhui-REGION-rhel-server-releases
Feb 01 14:29:10 ip-10-0-136-253.ec2.internal cloud-init[1530]: : rhui-REGION-rhel-server-rh-common
Feb 01 14:29:10 ip-10-0-136-253.ec2.internal cloud-init[1530]: Cleaning up everything
Feb 01 14:29:10 ip-10-0-136-253.ec2.internal cloud-init[1530]: Maybe you want: rm -rf /var/cache/yum, to also free up space taken by orphaned data from disabled or removed repos
Feb 01 14:29:11 ip-10-0-136-253.ec2.internal cloud-init[1530]: parse error: Invalid numeric literal at line 1, column 53
Feb 01 14:29:11 ip-10-0-136-253.ec2.internal cloud-init[1530]: + ((  __current_try == __tries  ))
Feb 01 14:29:11 ip-10-0-136-253.ec2.internal cloud-init[1530]: + echo 'Tried 20 times and failed!'
Feb 01 14:29:11 ip-10-0-136-253.ec2.internal cloud-init[1530]: Tried 20 times and failed!
Feb 01 14:29:11 ip-10-0-136-253.ec2.internal cloud-init[1530]: + return 1
Feb 01 14:29:11 ip-10-0-136-253.ec2.internal cloud-init[1530]: + qs_err ' Openshift installation failed, see logs for details '
Feb 01 14:29:11 ip-10-0-136-253.ec2.internal cloud-init[1530]: + touch /var/tmp/stack_failed
Feb 01 14:29:11 ip-10-0-136-253.ec2.internal cloud-init[1530]: + echo '[FAILED] @  Openshift installation failed, see logs for details '
Feb 01 14:29:11 ip-10-0-136-253.ec2.internal cloud-init[1530]: + echo '[FAILED] @  Openshift installation failed, see logs for details '
Feb 01 14:29:11 ip-10-0-136-253.ec2.internal cloud-init[1530]: [FAILED] @  Openshift installation failed, see logs for details
Feb 01 14:29:11 ip-10-0-136-253.ec2.internal cloud-init[1530]: ++ qs_status
Feb 01 14:29:11 ip-10-0-136-253.ec2.internal cloud-init[1530]: ++ '[' -f /var/tmp/stack_failed ']'
Feb 01 14:29:11 ip-10-0-136-253.ec2.internal cloud-init[1530]: ++ printf 1
Feb 01 14:29:11 ip-10-0-136-253.ec2.internal cloud-init[1530]: ++ return 1
Feb 01 14:29:11 ip-10-0-136-253.ec2.internal cloud-init[1530]: + cfn-signal -e 1 --stack Red-Hat-OpenShift-OpenShiftStack-1LNSTE6BH1WIJ --resource AnsibleConfigServer --region us-east-1
Feb 01 14:29:11 ip-10-0-136-253.ec2.internal cloud-init[1530]: Cloud-init v. 0.7.9 finished at Fri, 01 Feb 2019 14:29:11 +0000. Datasource DataSourceEc2.  Up 486.64 seconds
[root@ip-10-0-136-253 log]# 
```

Any guidance on what to try next? This failed with both 3.10 and 3.11. 

AWSServiceBroker | Enabled | -
AmiId | - | -
AnsibleFromGit | False | -
AutomationBroker | Enabled | -
AvailabilityZones | us-east-1a,us-east-1b,us-east-1c | -
ClusterConsole | Enabled | -
ClusterName | - | -
ContainerAccessCIDR | 0.0.0.0/0 | -
DomainName | - | -
EtcdInstanceType | m4.xlarge | -
GlusterFS | Disabled | -
GlusterInstanceType | i3.large | -
GlusterStorageEncrypted | false | -
GlusterStorageIops | 3000 | -
GlusterStorageSize | 1000 | -
GlusterStorageType | io1 | -
HawkularMetrics | Enabled | -
HostedZoneID | - | -
KeyPairName | splunk-openshift | -
MasterInstanceType | m4.xlarge | -
NodesInstanceType | m4.xlarge | -
NumberOfEtcd | 3 | -
NumberOfGluster | 3 | -
NumberOfMaster | 3 | -
NumberOfNodes | 3 | -
OpenShiftAdminPassword | **** | -
OpenshiftContainerPlatformVersion | 3.10 | -
OutputBucketName | - | -
PrivateSubnet1CIDR | 10.0.0.0/19 | -
PrivateSubnet2CIDR | 10.0.32.0/19 | -
PrivateSubnet3CIDR | 10.0.64.0/19 | -
PublicSubnet1CIDR | 10.0.128.0/20 | -
PublicSubnet2CIDR | 10.0.144.0/20 | -
PublicSubnet3CIDR | 10.0.160.0/20 | -
QSS3BucketName | aws-quickstart | -
QSS3KeyPrefix | quickstart-redhat-openshift/ | -
RedhatSubscriptionPassword | **** | -
RedhatSubscriptionPoolID | REDACTED | -
RedhatSubscriptionUserName | REDACTED | -
RemoteAccessCIDR | 0.0.0.0/0 | -
SubDomainPrefix | - | -
VPCCIDR | 10.0.0.0/16 | -

**Comment by klacuska** [comment]
what's in line 1 column 53?

I guess, it fails during jq parsing, so it seems to be a problem with parsing of one of following parameters:
user/password/poolid

**Comment by matthewmodestino** [comment]
Any tips on how to validate??

**Comment by hectoralicea** [comment]
I'm having a hard time just trying to figure out which poolid to use, in my subscription.
