### ISSUE TITLE
The following resource(s) failed to create: [AnsibleConfigServer] 

### ISSUE THREAD

**Issue by manindrabh** [aws-quickstart/quickstart-redhat-openshift#226]
Creating stack using the quick start templates started failing. We were able to create a stack successfully without any issues 3 days ago.

From the stack events, I see below error.
"Received FAILURE signal with UniqueId i-xxxxxxx"

I have verified the log files on the instance and found below error in /var/log/messages file

---------
Mar  1 15:29:56 ip-10-0-141-59 cloud-init: Error: Package: 1:java-1.8.0-openjdk-headless-1.8.0.201.b09-0.el7_6.x86_64 (rhel-7-server-rpms)
Mar  1 15:29:56 ip-10-0-141-59 cloud-init: Requires: pcsc-lite-devel(x86-64)
Mar  1 15:29:56 ip-10-0-141-59 cloud-init: **********************************************************************
Mar  1 15:29:56 ip-10-0-141-59 cloud-init: yum can be configured to try to resolve such errors by temporarily enabling
Mar  1 15:29:56 ip-10-0-141-59 cloud-init: disabled repos and searching for missing dependencies.
Mar  1 15:29:56 ip-10-0-141-59 cloud-init: To enable this functionality please set 'notify_only=0' in /etc/yum/pluginconf.d/search-disabled-repos.conf
Mar  1 15:29:56 ip-10-0-141-59 cloud-init: **********************************************************************
Mar  1 15:29:56 ip-10-0-141-59 cloud-init: Error: Package: 1:java-1.8.0-openjdk-headless-1.8.0.201.b09-0.el7_6.x86_64 (rhel-7-server-rpms)
Mar  1 15:29:56 ip-10-0-141-59 cloud-init: Requires: pcsc-lite-devel(x86-64)
Mar  1 15:29:56 ip-10-0-141-59 cloud-init: You could try using --skip-broken to work around the problem
Mar  1 15:29:56 ip-10-0-141-59 cloud-init: You could try running: rpm -Va --nofiles --nodigest
Mar  1 15:29:56 ip-10-0-141-59 cloud-init: + ((  __current_try == __tries  ))
Mar  1 15:29:56 ip-10-0-141-59 cloud-init: + echo 'Retrying ....'
---------

The package "java-1.8.0-openjdk-headless-1.8.0.201.b09-0.el7_6.x86_64" which failed to install was included in the bootstrap.sh script.

---------
qs_retry_command 10 yum install -y httpd-tools java-1.8.0-openjdk-headless
---------

CloudFormation tried to install the package 10 times and finally sent a Failure signal back to stack.

Researching more on the package that failed to install, I found few other people reported issue with the package in last 24 hours.
https://access.redhat.com/solutions/3949501
https://stackoverflow.com/questions/54936604/aws-cant-install-java-1-8-on-rhel

Can you please look into the issue and try to find a workaround to the issue?

**Comment by jaymccon** [comment]
I believe https://github.com/aws-quickstart/quickstart-redhat-openshift/commit/c1a36de4bf56d5694252fcaa5be1012da92180f0 should address this, can you confirm that you are still facing this issue when launching from the latest master branch or the current template linked from the deployment guide?

**Comment by edwardcallahan** [comment]
Thanks @jaymccon. That diff worked for me.
