### ISSUE TITLE
Ansible cannot connect over SSH

### ISSUE THREAD

**Issue by kemra102** [aws-quickstart/quickstart-redhat-openshift#23]
Ive been using this template to build OpenShift within an existing VPC in Frankfurt. Most of the build is getting done, it's just failing at the last (?) major hurdle. Actually running Ansible comes back with this error:

```
Nov 28 15:13:28 localhost cloud-init: 10.0.2.146 | UNREACHABLE! => {
Nov 28 15:13:28 localhost cloud-init: "changed": false,
Nov 28 15:13:28 localhost cloud-init: "msg": "SSH Error: data could not be sent to remote host \"10.0.2.146\". Make sure this host can be reached over ssh",
Nov 28 15:13:28 localhost cloud-init: "unreachable": true
Nov 28 15:13:28 localhost cloud-init: }
```
The hosts are certainly reachable. Turning off pipelining or trying SSH manually gives a key error such as:

```
Nov 28 15:13:53 localhost cloud-init: 10.0.1.118 | UNREACHABLE! => {
Nov 28 15:13:53 localhost cloud-init: "changed": false,
Nov 28 15:13:53 localhost cloud-init: "msg": "Failed to connect to the host via ssh: Permission denied (publickey,gssapi-keyex,gssapi-with-mic).\r\n",
Nov 28 15:13:53 localhost cloud-init: "unreachable": true
Nov 28 15:13:53 localhost cloud-init: }
```

I had assumed that the `KeyGen` & `GetRSA` components of the stack handled creation of keys that were then injected in to be used. Clearly something isn't working as intended. Where should I be looking to resolve this issue?

**Comment by kemra102** [comment]
I've dug into this quite a bit more today and as best I can tell there may be 2 issues causing this:

* The SSH Private Key on the Ansible box does not match the public key in the OpenShift instance's authorized_keys.
* The ansible command runs as root but root login is not allowed by default in RHEL AMIs.

I have pasted in the private key that matches the authorized_keys on the OpenShift instance's and this got me the following error message:

```
Nov 29 19:51:31 localhost cloud-init: 10.40.3.155 | FAILED! => {
Nov 29 19:51:31 localhost cloud-init: "changed": false,
Nov 29 19:51:31 localhost cloud-init: "failed": true,
Nov 29 19:51:31 localhost cloud-init: "module_stderr": "",
Nov 29 19:51:31 localhost cloud-init: "module_stdout": "Please login as the user \"ec2-user\" rather than the user \"root\".\n\n",
Nov 29 19:51:31 localhost cloud-init: "msg": "MODULE FAILURE",
Nov 29 19:51:31 localhost cloud-init: "rc": 0
Nov 29 19:51:31 localhost cloud-init: }
```
On a node where I've removed the echo that blocks root access the logs show:
```
Nov 29 19:53:17 localhost cloud-init: 10.40.2.127 | SUCCESS => {
Nov 29 19:53:17 localhost cloud-init: "changed": false,
Nov 29 19:53:17 localhost cloud-init: "failed": false,
Nov 29 19:53:17 localhost cloud-init: "ping": "pong"
Nov 29 19:53:17 localhost cloud-init: }
```

**Comment by avattathil** [comment]
Are you comparing the root user or the ec2users keys ?

**Comment by kemra102** [comment]
The root user on both boxes. `cloud-init` seems to run as root and therefore so does Ansible.

**Comment by avattathil** [comment]
Let me attempt to recreate this issues.

**Comment by avattathil** [comment]
@kemra102 , I added the eu-central-1 updates to the latest version. 
 _Live here:_ https://aws.amazon.com/quickstart/architecture/openshift/

I also tested it to make sure I can ping the hosts from the ansible control host and also successfully complete a cluster build. 
Please see the screenshots below:
![eu-centeral-1](https://user-images.githubusercontent.com/5912128/33417032-7b4cfe4e-d554-11e7-9049-285c277e5222.jpg)
 
Also here is a snippet of the log showing the completed build. 
![eu-centeral-2](https://user-images.githubusercontent.com/5912128/33417057-9981d75e-d554-11e7-9d3b-19f717aac684.jpg)

**Comment by kemra102** [comment]
This seems to be working now, many thanks.
