### ISSUE TITLE
openshiftetcdASG creation fails and everything rolls back. 

### ISSUE THREAD

**Issue by danseo-reisys** [aws-quickstart/quickstart-redhat-openshift#232]
Please review following error and provide some guidance.  Thanks. 

04 Apr 2019 17:32:40	Red-Hat-OpenShift-OpenShiftStack-1EYTSYFQJ6021	
CREATE_FAILED	The following resource(s) failed to create: [OpenShiftNodeASG, AnsibleConfigServer, OpenShiftEtcdASG, OpenShiftMasterASG].
04 Apr 2019 17:32:38	AnsibleConfigServer	
CREATE_FAILED	Resource creation cancelled
04 Apr 2019 17:32:37	OpenShiftMasterASG	
CREATE_FAILED	Resource creation cancelled
04 Apr 2019 17:32:37	OpenShiftNodeASG	
CREATE_FAILED	Resource creation cancelled
04 Apr 2019 17:32:35	OpenShiftEtcdASG	
CREATE_FAILED	Received 0 SUCCESS signal(s) out of 3. Unable to satisfy 100% MinSuccessfulInstancesPercent requirement
04 Apr 2019 17:32:34	OpenShiftEtcdASG	
UPDATE_IN_PROGRESS	Failed to receive 3 resource signal(s) for the current batch. Each resource signal timeout is counted as a FAILURE.

**Comment by danseo-reisys** [comment]
Under EC2, I saw all the new VMs up and running when this happened.

**Comment by danseo-reisys** [comment]
i disabled rollback and looked at errors.  the errors were related to redhat subscription.   i'm trying to get more subscription now.

**Comment by danseo-reisys** [comment]
for now i'm going with OKD instance.

**Comment by danseo-reisys** [comment]
i have tried this again.  I see followings repeating on ansible-config 

Apr 12 19:14:22 ip-10-0-143-50.ec2.internal cloud-init[1610]: Registering to: subscription.rhsm.redhat.com:443/subscript
ion
Apr 12 19:14:22 ip-10-0-143-50.ec2.internal cloud-init[1610]: Retrying ....
Apr 12 19:14:59 ip-10-0-143-50.ec2.internal cloud-init[1610]: You must first accept Red Hat's Terms and conditions. Plea
se visit https://www.redhat.com/wapps/tnc/ackrequired?site=candlepin&event=signOn . You may have to log out of and back
into the  Customer Portal in order to see the terms.
Apr 12 19:14:59 ip-10-0-143-50.ec2.internal cloud-init[1610]: Registering to: subscription.rhsm.redhat.com:443/subscript
ion
Apr 12 19:14:59 ip-10-0-143-50.ec2.internal cloud-init[1610]: Retrying ....
Apr 12 19:15:38 ip-10-0-143-50.ec2.internal cloud-init[1610]: You must first accept Red Hat's Terms and conditions. Plea
se visit https://www.redhat.com/wapps/tnc/ackrequired?site=candlepin&event=signOn . You may have to log out of and back
into the  Customer Portal in order to see the terms.
Apr 12 19:15:38 ip-10-0-143-50.ec2.internal cloud-init[1610]: Registering to: subscription.rhsm.redhat.com:443/subscript
ion
Apr 12 19:15:38 ip-10-0-143-50.ec2.internal cloud-init[1610]: Retrying ....
Apr 12 19:16:20 ip-10-0-143-50.ec2.internal cloud-init[1610]: You must first accept Red Hat's Terms and conditions. Plea
se visit https://www.redhat.com/wapps/tnc/ackrequired?site=candlepin&event=signOn . You may have to log out of and back
into the  Customer Portal in order to see the terms.

Doesn't the cloudformation take care of term acceptance?

**Comment by skaminskitx** [comment]
The cloudformation will not take care of the term acceptance.  You'll need to do that on the RH Portal.  Ran into this previously.

**Comment by danseo-reisys** [comment]
issued fixed for me.  diable stack rollback and check ansible config server log.  my issue was on redhat subscriptions
