### ISSUE TITLE
Question: How to make Console Private

### ISSUE THREAD

**Issue by shadycuz** [aws-quickstart/quickstart-redhat-openshift#25]
My Environment is connected to AWS. I have made the Public Master ELB Internal. How do I handle `openshift_master_cluster_public_hostname` in the ansible config server userdata? Is it safe to remove?

I have this 
```
MASTER_ELBDNSNAME=${OpenShiftMasterInternalELB.DNSName}
INTERNAL_MASTER_ELBDNSNAME=${OpenShiftMasterInternalELB.DNSName}
NODE_ELBDNSNAME=${OpenShiftNodeInternalELB.DNSName}
echo "[INFO] Configuring OpenShift Variable" 
echo openshift_master_cluster_hostname=${!INTERNAL_MASTER_ELBDNSNAME} >> /etc/ansible/hosts 
echo openshift_master_cluster_public_hostname=${!MASTER_ELBDNSNAME} >> /etc/ansible/hosts 
echo openshift_hostname=${!INTERNAL_MASTER_ELBDNSNAME} >> /etc/ansible/hosts 
```

I also noticed you set NODE_ELBDNSNAME but never use it?

**Comment by avattathil** [comment]
I have not tested these changes. I would comment it out and restart the cluster to make sure there are no advise effect before making permanent modifications.
