### ISSUE TITLE
Template error: Fn::Select cannot select nonexistent value at index 2

### ISSUE THREAD

**Issue by adnsid** [aws-quickstart/quickstart-redhat-openshift#263]
Quickstart on launching on OpenShift for new VPC is failing with the error message: 

Template error: Fn::Select cannot select nonexistent value at index 2

**Comment by vsnyc** [comment]
@adnsid Did you supply three AZs for the `AvailabilityZones` parameter?

**Comment by adnsid** [comment]
@vsnyc Thank you - that was the issue - I did not realize I needed to specify three AZs seperately
