### ISSUE TITLE
Quickstart for 4.3 fails - multiple issues

### ISSUE THREAD

**Issue by yagachi** [aws-quickstart/quickstart-redhat-openshift#270]
Hi,
I am trying to deploy Openshift 4.3 using AWS Quickstart.

I am using the following CLoudFormation template: 
https://aws-quickstart.s3.amazonaws.com/quickstart-redhat-openshift/templates/openshift-main.template.yaml

Reference Document:  https://aws-quickstart.s3.amazonaws.com/quickstart-redhat-openshift/doc/red-hat-openshift-on-the-aws-cloud.pdf 

Just an FYI, my cluster name is `sumayafail`. Not to be mistaken for an actual failure :) 

I am facing a couple of issues:
1. The default parameter for `QSS3KeyPrefix`  comes up as  `quickstart-redhat-openshift-4.3-preview/` which results in an error saying s3 object not found. So I changed it to `quickstart-redhat-openshift/` as per this document https://aws-quickstart.s3.amazonaws.com/quickstart-redhat-openshift/doc/red-hat-openshift-on-the-aws-cloud.pdf and the stack started to build.
2. The create stack starts of well but fails with the  below error.
`Embedded stack arn:aws:cloudformation:ap-southeast-2:000987835229:stack/sumaya06qs-OpenShift4-1MO1LC13V9I10/b422e130-0e1c-11eb-bd1d-0a68ae7ab724 was not successfully created: The following resource(s) failed to create: [OpenShiftGenerateIgnition]. `

![image](https://user-images.githubusercontent.com/14071628/96237945-cb487800-0f95-11eb-8f71-6c6a8923c549.png)

The failure is at nested stack `OpenShift4`
![image](https://user-images.githubusercontent.com/14071628/96238297-3abe6780-0f96-11eb-9340-4c835325d693.png)
![image](https://user-images.githubusercontent.com/14071628/96238416-5aee2680-0f96-11eb-871c-1af2b5a8e131.png)

3. Here are the cloudwatch logs
Looks like the logGroup is hardcoded  here which is causing logs of one cloudFormation run to show up in another run logs.
https://github.com/aws-quickstart/quickstart-redhat-openshift/blob/2e3ed8d14ba344c98cf757729c82fe3512ecba8d/templates/common/custom_lambda.template.yaml#L585
![image](https://user-images.githubusercontent.com/14071628/96239500-b1a83000-0f97-11eb-90dd-3f752596bc2c.png)

![image](https://user-images.githubusercontent.com/14071628/96239277-67bf4a00-0f97-11eb-8d64-bb5ceb608651.png)

![image](https://user-images.githubusercontent.com/14071628/96239143-43636d80-0f97-11eb-8551-13232a20c323.png)

4. I tried to copy the github code from this repository as is and placed it in s3 and started to cloudformation stack from my own s3 location. Looks like there are a few missing bits that I don't know how to generate.
For example: https://github.com/aws-quickstart/quickstart-redhat-openshift/blob/2e3ed8d14ba344c98cf757729c82fe3512ecba8d/templates/common/custom_lambda.template.yaml#L236
expects zipped files lambda.zip to be present in functions/packages/* path but the repository doesn't have them. Not sure how they are generated though. Not sure how to proceed to build Openshift 4.3 using quickstart.
I would expect it to working without having to change any code unless I have given wrong input values.

Could you please help.

Input Parameters:
```
AWSServiceBroker | Disabled
-- | --
AmiId | -
AnsibleFromGit | False
AutomationBroker | Enabled
AvailabilityZones | ap-southeast-2a,ap-southeast-2b,ap-southeast-2c
CertificateArn | -
ClusterConsole | Enabled
ClusterIngressCertificateArn | -
ClusterIngressPrivateKeySecretName | -
ClusterName | sumayafail
ContainerAccessCIDR | 0.0.0.0/0
DomainName | my_domain(changed here)
EnableSSLCertificateGeneration | no
EtcdInstanceType | m5.xlarge
GlusterFS | Disabled
GlusterInstanceType | i3.large
GlusterStorageEncrypted | False
GlusterStorageIops | 3000
GlusterStorageSize | 1000
GlusterStorageType | io1
HawkularMetrics | Enabled
HostedZoneID | XXXXXXXXX(changed here)
KeyPairName | -
MasterInstanceProfileName | -
MasterInstanceType | m5.xlarge
NodesInstanceType | m5.xlarge
NumberOfAZs | 3
NumberOfEtcd | 3
NumberOfGluster | 3
NumberOfMaster | 3
NumberOfNodes | 3
OpenShiftAdminPassword | ****
OpenshiftContainerPlatformVersion | 4.3
PrivateSubnet1CIDR | 10.0.0.0/19
PrivateSubnet2CIDR | 10.0.32.0/19
PrivateSubnet3CIDR | 10.0.64.0/19
PublicSubnet1CIDR | 10.0.128.0/20
PublicSubnet2CIDR | 10.0.144.0/20
PublicSubnet3CIDR | 10.0.160.0/20
PullSecret | ****
QSS3BucketName | aws-quickstart
QSS3BucketRegion | -
QSS3KeyPrefix | quickstart-redhat-openshift/
RedhatSubscriptionPassword | ****
RedhatSubscriptionPoolID | -
RedhatSubscriptionUserName | -
RemoteAccessCIDR | 0.0.0.0/0
SSHKey | my ssh key
SubDomainPrefix | -
VPCCIDR | 10.0.0.0/16
WorkerInstanceProfileName | -
```

**Comment by Vincent-Le** [comment]
I am also seeing this issue

**Comment by Alex-Murr** [comment]
Hi! It's happening to me too. How did you solve this? Why does the default template fails?

**Comment by Kadaeux** [comment]
Was this ever resolved? I'm seeing this issue as well.

**Comment by yagachi** [comment]
> 
> 
> Hi! It's happening to me too. How did you solve this? Why does the default template fails?

I did not resolve it. I started deploying Openshift using https://docs.openshift.com/container-platform/4.6/installing/installing_aws/installing-aws-customizations.html. That worked for me. So I did not bother looking into this further.
