### ISSUE TITLE
Unable to create storage volumes 

### ISSUE THREAD

**Issue by rkatti** [aws-quickstart/quickstart-redhat-openshift#28]
I run into this error when creating EBS backed storage on Openshift 3.6.173.0.5-5 created with the CF template.

I see the aws-ebs plugin loaded. Any suggestions ?

  | 11:17:00 AM | Warning | Provisioning failed | Failed to provision volume with StorageClass "aws-ebs-sc": Failed to get AWS Cloud Provider. GetCloudProvider returned <nil> instead
-- | -- | -- | -- | --

Following is my storage yaml definition :

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
  name: aws-ebs-sc
provisioner: kubernetes.io/aws-ebs

**Comment by ngerasimatos** [comment]
@rkatti Can you provide more information on how you are creating such? I want to try and duplicate this on my side so the more information you can provide the better.

**Comment by jvitlab** [comment]
I am creating the from one of the master node using : oc create -f sc.yaml 

Is there anything specifically you are looking for ?

**Comment by rkatti** [comment]
I fixed this problem by running configuring  adding following to openshift_config_ose.yml

openshift_cloudprovider_kind=aws
openshift_cloudprovider_aws_access_key=
openshift_cloudprovider_aws_secret_key=

and reruning  playbook on the ansible server  : ansible-playbook  --flush-cache  /usr/share/ansible/openshift-ansible/playbooks/byo/config.yml
