### ISSUE TITLE
ASG events drop nodes in cluster

### ISSUE THREAD

**Issue by avattathil** [aws-quickstart/quickstart-redhat-openshift#36]
If an instance dies, ASG recreates the node but not as a member of the OpenShift cluster.

**Comment by avattathil** [comment]
Fix for this is in the development led by @agamzn . This issue will be used to discuss any improvement to the fix

### Workflow to handle scaling events  

The scaling components of the AWS OpenShift QuickStart leverage AWS CloudWatch Events and the AWS SSM RunCmd module to invoke on-instance scripts to configure just-launched instances within the OpenShift Cluster. 

When an AutoScaling Group increases or reduces its capacity, a CloudWatch Event is triggered, sending a signal to a specific AWS SSM Target to execute a shell script. The specific target is the Ansible Config Server of the cluster, identified by Instance ID. The specific script executed within the Ansible Config Server is "/bin/aws-ose-qs-scale --scale-in-progress". 

Once this script is executed, it queries the EC2 AutoScaling APIs to determine any changes made to each of the Auto Scaling Groups within the cluster. If changes are found, the script takes appropriate action based on the events that have occured. 

In the case of a scale-up event, the script generates cluster-related metadata for the instance and adds it to the Ansible Hosts inventory located at /etc/ansible/hosts. Similarly, if instances have been removed from the cluster, their node definitions are removed from the Ansible Hosts Inventory. In the case of scale-up the next steps include verifying that each instance is reachable and then triggering the appropriate Ansible Playbook(s). 

Logging: 

The quickstart scaling scripts log workflow out to /var/log/openshift-quickstart-scaling.log. Ansible Playbook specific logs are stored in "/var/log/aws-quickstart-openshift-scaling.<YEAR>-<MONTH>-<DAY>T<HOUR><MINUTE>" format

**Comment by avattathil** [comment]
Scaling updates merged in this commit https://github.com/aws-quickstart/quickstart-redhat-openshift/commit/53bdd52e8b31766e8987d155efe3302af1b396c0

**Comment by philipakash** [comment]
@avattathil ^^ Is this tested fine Or should I wait for a release to use this feature in production ?

**Comment by avattathil** [comment]
We are working on some fixes in the develop branch. Hope to have them
released in a few weeks.

**Comment by philipakash** [comment]
Thanks @avattathil
