### ISSUE TITLE
features/include aws-servicebroker

### ISSUE THREAD

**Issue by avattathil** [aws-quickstart/quickstart-redhat-openshift#44]

**Comment by jaymccon** [comment]
initial implementation https://github.com/aws-quickstart/quickstart-redhat-openshift/commit/19ec43be444eb58e495b3046531441bdc3ecd4ca still needs work to get default secrets setup, and upstream work to use an instance-profile instead of credentials when `aws_access_key: 'use-role'`

**Comment by jaymccon** [comment]
aws=servicebroker will now use role if `aws_access_key: 'use-role'` is set in the secrets, https://github.com/awslabs/aws-servicebroker-s3/commit/7fc64d446b5e7d72f8f3ed192c2f87767a15e8db for example

**Comment by jaymccon** [comment]
implementation completed in https://github.com/aws-quickstart/quickstart-redhat-openshift/tree/feature/service-broker

will need some doc updates

**Comment by avattathil** [comment]
Closing,  doc updates tracked in https://github.com/aws-quickstart/quickstart-redhat-openshift/issues/37
