### ISSUE TITLE
features/use acm for certificates

### ISSUE THREAD

**Issue by avattathil** [aws-quickstart/quickstart-redhat-openshift#45]

**Comment by naumannt** [comment]
Would this be possible to do manually? We created OpenShift from a template, using self-signed certificates in the process to get it running. Using the ACM certificates on the ELBs of OpenShift leads to multiple connections failing (nodes not reachable from master, docker repository turns completely unreachable...). What is the correct way to implement ACMs with OpenShift?

**Comment by jaymccon** [comment]
@naumannt there is an initial implementation ( https://github.com/aws-quickstart/quickstart-redhat-openshift/tree/feature/acm ) that you could have a look at. 

As to the symptoms you mentioned (nodes not reachable from master, docker repository turns completely unreachable...) I would like to investigate further, can you provide any steps to help replicate ?

**Comment by naumannt** [comment]
We used AWS's Inbound-rules to apply a Amazon-signed certificate to all ELB's of OpenShift. This led to the master console becoming slow and displaying incomplete information. Using 'oc describe nodes' showed that the master was unable to reach any nodes. 
Removing the inbound 'https'-rules from the Load Balancers fixed the issue.

**Comment by jaymccon** [comment]
are you able to test using https://github.com/aws-quickstart/quickstart-redhat-openshift/tree/feature/acm ? 

I believe this should not display those symptoms, we used ssl instead of https on the ELB, only placed it on the OpenShiftMasterELB api and console ports, and updated the ansible config openshift_master_cluster_public_hostname entry to point to the custom domain name.

**Comment by naumannt** [comment]
Implemented SSL(TCP) on 443 for both opensh-InfraElb and opensh-Master, but not internal-opensh-Master. Browsers accept the certificate & the system seems to be running stable.

**Comment by naumannt** [comment]
Update: while the certificates for services and the master console were fixed by this, the docker registry and the registry console became completely unresponsive (public route only showing "The app is unaivalable"). 
Shouldn't the docker registry also be amanged by opensh-InfraElb?

**Comment by jaymccon** [comment]
@naumannt are you able to test using the [feature/acm](https://github.com/aws-quickstart/quickstart-redhat-openshift/tree/feature/acm) branch? 

I believe this was addressed in https://github.com/aws-quickstart/quickstart-redhat-openshift/commit/bce239df00f7be5a4ce1593004aa63232b90abbb by updating the listeners and security group for the ContainerAccessELB to allow 443 using SSL
