### ISSUE TITLE
features/offer route53 for dns (optional)

### ISSUE THREAD

**Issue by avattathil** [aws-quickstart/quickstart-redhat-openshift#46]

**Comment by mandusm** [comment]
### Proposed Decision Tree for the configuration of  default subdomain to use for exposed routes
```openshift_master_default_subdomain```
1: Customer provides a Delegated Route53 Hosted Zone Id
2: Customer provides a string from a domain set up through an external provider pointing to ELB
3: If neither 1/2 is provided by customer, deploy using a wildcard provider like nip.io

**Comment by jaymccon** [comment]
implemented here https://github.com/aws-quickstart/quickstart-redhat-openshift/tree/feature/route53

@mandusm I didn't do the nip.io part, here's what we got:

3 parameters, DomainName, HostedZoneID, and Subdomain. 

If HostedZoneID is not provided, we assume DNS will be setup externally and simply inform the cluster of the hostname (this will be documented in the deployment guide).

If Subdomain and HostedZoneID is provided we create a dedicated hostedzone using the subdomain and put master elb at apex and router elb at wildcard. If Subdomain is not specified we create the records in the existing hosted zone.

**Comment by gamkiller77** [comment]
I really need this feature for a demo I am doing at work.  I see Release v1.3 is a bit out there but what the best way to get subdomain integration setup?  Having a single exposed app is not going to cut it for me.

**Comment by jaymccon** [comment]
@gamkiller77 just a heads up, we've hit a few bugs that have delayed v1.3 from getting to a usable state, as soon as we're there I'll post some instructions on doing a build from the release branch

**Comment by avattathil** [comment]
Finalizing, updates in release branch (develop)
