### ISSUE TITLE
features/setup ebs as default persistent store

### ISSUE THREAD

**Issue by avattathil** [aws-quickstart/quickstart-redhat-openshift#48]

**Comment by jaymccon** [comment]
implemented in https://github.com/aws-quickstart/quickstart-redhat-openshift/commit/c97c5dcd7305c7d3c400de2af3d088f321e1ad34 and https://github.com/aws-quickstart/quickstart-redhat-openshift/commit/e452f167859af76a2a01dd0565690caec383a168
