### ISSUE TITLE
Autoscaling down/up mechanism 

### ISSUE THREAD

**Issue by philipho11** [aws-quickstart/quickstart-redhat-openshift#54]
Here are steps that I performed:

1. Adjusted "OpenShiftMasterASG", "OpenShiftEtcdASG" and "OpenShiftNodeASG" to zero after office hours. 

2. In morning, adjusted  the desired capacity on the "OpenShiftMasterASG" first by setting it to 3. Then only after these instances have finished booting (estimate 5 or more minutes) try to increase the desired capacity on the other two Auto Scaling Groups, "OpenShiftEtcdASG" and "OpenShiftNodeASG". 

3. The GUI is not accessible. Not sure if the underlying Openshift services are working.

The other hint is that in the bastion hosts ansible hosts file, more groups of nodes are created (see below) but provisioning just stopped there. 

[root@ip-10-0-137-180 log]# grep "\[" /etc/ansible/hosts 
[OSEv3:children]
[OSEv3:vars]
openshift_master_identity_providers=[{'name': 'htpasswd_auth', 'login': 'true', 'challenge': 'true', 'kind': 'HTPasswdPasswordIdentityProvider', 'filename': '/etc/origin/master/htpasswd'}]
[etcd]
[masters]
[nodes]
[new_nodes]
[provision_in_progress]
[new_masters]
[new_etcd]

Can auto-scaling works in some sunny day cases? It is okay if we can autoscaling to 1 or 2 so as to at least save some costs while Openshift users are still being identified in my enterprise.

**Comment by jaymccon** [comment]
Hi,

OpenShiftEtcdASG cannot be scaled down below 2 nodes without loosing data and destroying the install (have a look at the [etcd faq](https://coreos.com/etcd/docs/latest/faq.html#what-is-failure-tolerance).

You should be able to scale the OpenShiftMasterASG and OpenShiftNodeASG down to 0 though.

**Comment by philipho11** [comment]
jaymccon, 

The verified case is to update cloudformation stack or direclty go to OpenshiftMasterASG and set the minimum and desired to 0?

**Comment by jaymccon** [comment]
Quickstarts do not support updating the cloudformation stack, so you should be using the autoscaling api/cli/console directly.

I'm going to mark this as closed, please feel free to re-open if you experience any issues with the approach.
