### ISSUE TITLE
Fail to run template due to creating IAM users/groups with full admin access

### ISSUE THREAD

**Issue by alin27** [aws-quickstart/quickstart-redhat-openshift#57]
Hey, we ran and deployed the template successfully about 2 weeks ago on AWS, but when I tried to run it again today it failed because the template was asking permission to create IAM users/groups with full admin access (needed for Lambda at a quick glance?). We don't have permission to create IAM users, so was wondering what those IAM roles are for and what policies need to be in place to run the template? Hope there is a workaround this.

**Comment by jaymccon** [comment]
The role is for the recently released [AWS Service Broker](https://github.com/awslabs/aws-servicebroker-documentation/wiki). The broker enabled the creation of AWS resources directly in openshift, and as such requires an administrative role. 

At the moment the broker is disabled, but the role is not, I will setup a condition to disable the role. Once the broker is enabled in the quickstart it will be a parameter which you can disable if needed.

**Comment by jaymccon** [comment]
fix in place https://github.com/aws-quickstart/quickstart-redhat-openshift/commit/bd2626d1c586eae5c294234b6cec97402d46f94b, it may take some time for the ci to run and get this into master and into the quickstart bucket, but you build off the develop branch in the meantime if you'd like.
