### ISSUE TITLE
Autoscale Error 

### ISSUE THREAD

**Issue by waynedovey** [aws-quickstart/quickstart-redhat-openshift#58]
Seeing this error when one of the nodes in the ASG is killed. 

Traceback (most recent call last):\n  File \"/bin/aws-ose-qs-scale\", line 14, in \u003cmodule\u003e\n    sys.exit(main())\n  File \"/bin/aws-ose-qs-scale\", line 11, in main\n    return aws_openshift_quickstart.scaler.main()\n  File \"/usr/lib/python2.7/site-packages/aws_openshift_quickstart/scaler.py\", line 195, in main\n    InventoryConfig.populate_from_ansible_inventory()\n  File \"/usr/lib/python2.7/site-packages/aws_openshift_quickstart/utils.py\", line 123, in populate_from_ansible_inventory\n    _instance_id = _pattern.search(inventory_config.get(subcategory, key))\nTypeError: expected string or buffer\n\nfailed to run commands: exit status 1"

**Comment by agamzn** [comment]
@waynedovey , looking into this.

**Comment by agamzn** [comment]
Hey @waynedovey , I have a hunch what's causing this. I'll keep digging in the background. Just in case you are monitoring this thread, can you provide the contents of your /etc/ansible/hosts ?

**Comment by waynedovey** [comment]
Hey @agamzn , Here is my current hosts file. Let me know if you need anymore details. Thanks

# AWS QuickStart OpenShift Installation
#
# Create an OSEv3 group that contains the masters, nodes, and etcd groups
[OSEv3:children]
masters
nodes
etcd

# Set variables common for all OSEv3 hosts
[OSEv3:vars]
ansible_ssh_user=root
openshift_deployment_type=openshift-enterprise
containerized=false
openshift_master_cluster_method=native
openshift_clock_enabled=true
openshift_router_selector='router_node=yes'
openshift_registry_selector='registry_node=yes'
osm_default_node_selector='application_node=yes'
openshift_clusterid=owned
openshift_cloudprovider_kind=aws

openshift_master_identity_providers=[{'name': 'htpasswd_auth', 'login': 'true', 'challenge': 'true', 'kind': 'HTPasswdPasswordIdentityProvider', 'filename': '/etc/origin/master/htpasswd'}]


openshift_master_cluster_hostname=internal-Red-Hat-O-OpenShif-DUGT96KWC24J-1701807850.ap-southeast-2.elb.amazonaws.com
openshift_master_cluster_public_hostname=Red-Hat-O-OpenShif-ULF1PLAMWDHT-346108649.ap-southeast-2.elb.amazonaws.com
[etcd]
ip-10-0-55-103.ap-southeast-2.compute.internal                              # i-00c5770f4517e32c7
ip-10-0-76-136.ap-southeast-2.compute.internal                              # i-01cfd268b07c88983
ip-10-0-12-130.ap-southeast-2.compute.internal                              # i-05047006d721ef730

[masters]
ip-10-0-95-210.ap-southeast-2.compute.internal                            openshift_node_labels="{'region': 'primary', 'zone': 'default'} " openshift_schedulable=false # i-026ca75d5e6e1bf54
ip-10-0-19-209.ap-southeast-2.compute.internal                            openshift_node_labels="{'region': 'primary', 'zone': 'default'} " openshift_schedulable=false # i-04a810bf1a4fc2fa6
ip-10-0-57-91.ap-southeast-2.compute.internal                            openshift_node_labels="{'region': 'primary', 'zone': 'default'} " openshift_schedulable=false # i-05a39e93048f1a452

[nodes]
ip-10-0-95-210.ap-southeast-2.compute.internal                            openshift_node_labels="{'region': 'primary', 'zone': 'default'} " openshift_schedulable=false # i-026ca75d5e6e1bf54
ip-10-0-19-209.ap-southeast-2.compute.internal                            openshift_node_labels="{'region': 'primary', 'zone': 'default'} " openshift_schedulable=false # i-04a810bf1a4fc2fa6
ip-10-0-57-91.ap-southeast-2.compute.internal                            openshift_node_labels="{'region': 'primary', 'zone': 'default'} " openshift_schedulable=false # i-05a39e93048f1a452
ip-10-0-29-57.ap-southeast-2.compute.internal                            openshift_node_labels="{'application_node': 'yes', 'registry_node': 'yes', 'router_node': 'yes', 'region': 'infra', 'zone': 'default'} "  # i-0967683049d420636
ip-10-0-95-214.ap-southeast-2.compute.internal                            openshift_node_labels="{'application_node': 'yes', 'registry_node': 'yes', 'router_node': 'yes', 'region': 'infra', 'zone': 'default'} "  # i-0a0b1f9fa37eff31b
ip-10-0-36-6.ap-southeast-2.compute.internal                            openshift_node_labels="{'application_node': 'yes', 'registry_node': 'yes', 'router_node': 'yes', 'region': 'infra', 'zone': 'default'} "  # i-0a95ee5ce6bea8bae

**Comment by agamzn** [comment]
Thanks. Bug confirmed. 

The issue here is the line it errors on. 

https://github.com/aws-quickstart/quickstart-redhat-openshift/blob/5846df6dc4efd04119281d42779d6406401bebc7/scripts/scaling/aws_openshift_quickstart/utils.py#L123

It's doing a regex search for the instance ID. The `inventory_config.get()` reference is because the host definition within `/etc/ansible/hosts` is parsed  as an INI file. Each host entry is subsequently split into key/value pairs... sometimes. 

Expected behavior looks like this, where the combined key/value pair comprises of the entire host line within the inventory. The current code searches the 'value' half for the Instance ID. 

```
>>> key
'ip-10-0-89-249.us-west-2.compute.internal                            openshift_node_labels'
>>> inventory_config.get(subcategory, key)
'"{\'region\': \'primary\', \'zone\': \'default\'} " openshift_schedulable=false # i-06476f88bd5dced93'
>>> 
```

What's occurring here is that there's no value for the key. 

```
>>> foo = inventory_config.get(subcategory, key)                                                                                
>>>_pattern.search(foo).group()                                        
Traceback (most recent call last):    
  File "<pudb command line>", line 1, in <module>
TypeError: expected string or buffer 
>>> _pattern.search(foo).group() 
```

We expect the instance ID to be in the value, where infact, everything's shoved into the key. 

```
>>> _pattern.search(key).group()          
'i-048723168f7057fa8' 
```

I'm working on a fix now. It shouldn't be more than a few lines of modification. However I do need to put it through our CI/CD Paces so it may be a little bit before the fix is pushed to master. 

That said - I'll fast-track it as much as I can. Thanks for reporting this.

**Comment by agamzn** [comment]
Confirmed with @waynedovey via out-of-band that the commits in issue-58 branch have resolved this. PR forthcoming.
