### ISSUE TITLE
add debug parameter to the cfn template

### ISSUE THREAD

**Issue by jaymccon** [aws-quickstart/quickstart-redhat-openshift#73]
add a debugging flag for the scaling code, so that if one runs into issues the stack can easily be relaunched with debug logs enabled, which will modify all calls to the `bin/aws-ose-qs-scale` script to add the `--debug` flag

**Comment by avattathil** [comment]
Addressed in https://github.com/aws-quickstart/quickstart-redhat-openshift/pull/85
