### ISSUE TITLE
RHN poolid required?

### ISSUE THREAD

**Issue by dougtoppin** [aws-quickstart/quickstart-redhat-openshift#9]
The Quick Start Reference Deployment document says that an RHN poolid is required but does not provide any information on what that is nor how to get one. If I go to my rh account subscriptions page it says that one can be purchased but I am guessing that is not what is necessary for this quickstart.

**Comment by avattathil** [comment]
@dougtoppin I will add this to the documentation. 
Please see the information here on how to find the pool it. https://access.redhat.com/solutions/2434941

I suggest launching a RHEL7 ec2 instance and running the following commands:

`sudo subscription-manager --username=rhnusername --password=yourpassword`
`sudo subscription-manager list --available` # this will list you pool id

If you don't see OpenShift in the list you need signup for a trial or acquire a license.

Let me know if you need further assistance

Thanks
--Tony

**Comment by ngerasimatos** [comment]
You can also get the pool id information from the red hat subscription portal. 

https://access.redhat.com/management/

**Comment by ngerasimatos** [comment]
If you need a 30-day trial subscription, it can be found here: 

https://www.redhat.com/wapps/eval/index.html?evaluation_id=1026

**Comment by dougtoppin** [comment]
tks for the replies. I have a few suggestions on the README and will PR it in the next day or so to see what you think. They will mostly revolve around some overview of what is needed before someone tries it.

**Comment by avattathil** [comment]
Further status in https://github.com/aws-quickstart/quickstart-redhat-openshift/pull/10
Current Status: _Pending legal review_

**Comment by mandibuswell** [comment]
The main issue is that if you do not have a RHEL install already done then how do you get the Pool ID. You must provide it to Cloudformation template else it will not work, So is there a way to determine the pool id without having access to a RHEL machine to run the subscription-manager query.

**Comment by jaymccon** [comment]
@mandibuswell you can also get it from the redhat customer portal:

1. login to https://access.redhat.com
2. click on "My Subscriptions"
3. click on "Active" just below "Subscription Utilization"
4. Type "Red Hat OpenShift Container Platform" into the filter field and press enter
5. Click on the Subscription Number for the subscription you would like to use
6. PoolId is displayed in the "Pool IDs section"
