### ISSUE TITLE
Can't remove EBS pv

### ISSUE THREAD

**Issue by jaymccon** [aws-quickstart/quickstart-redhat-openshift#91]
copied the following from https://github.com/aws-quickstart/quickstart-redhat-openshift/issues/90#issuecomment-374829481

@philipho11 reported:

I also tried to create a separate storage in GUI. The EBS can launch okay. But when I delete the storage in GUI, the oc get pv shows fail status. Attached is the log too. Something wrong with persistent storage?

![screenshot from 2018-03-21 12-06-51](https://user-images.githubusercontent.com/10525442/37694223-67b4ca70-2d00-11e8-94eb-ac26a0ad2b14.png)

**Comment by jaymccon** [comment]
@philipho11 this should be addressed in 380041d 

I will close this for now, if you continue to experience issues with volume deletion please feel free to re-open

**Comment by philipho11** [comment]
Fixed. Thank you!
