### ISSUE TITLE
Registry console URL cannot be accessed

### ISSUE THREAD

**Issue by philipho11** [aws-quickstart/quickstart-redhat-openshift#93]
Registry console cannot be accessed. Below is some logs from pod. Do need to add 9090 port to ELB?

[root@ip-10-0-31-15 ~]# oc get pods
NAME                       READY     STATUS    RESTARTS   AGE
docker-registry-1-5cn88    1/1       Running   0          22m
registry-console-1-mdfjf   1/1       Running   0          22m
router-1-vh8xt             1/1       Running   0          24m
[root@ip-10-0-31-15 ~]# 
[root@ip-10-0-31-15 ~]# oc logs po/registry-console-1-mdfjf
INFO: cockpit-ws: Using certificate: /etc/cockpit/ws-certs.d/0-self-signed.cert
[root@ip-10-0-31-15 ~]# oc logs po/registry-console-1-mdfjf
Unable to connect to the server: net/http: TLS handshake timeout
[root@ip-10-0-31-15 ~]# oc logs po/registry-console-1-mdfjf
INFO: cockpit-ws: Using certificate: /etc/cockpit/ws-certs.d/0-self-signed.cert

**Comment by jaymccon** [comment]
Hi @philipho11,

The registry console is on port 9000, if you would like to make this accessible from outside the cluster VPC then, as you suggested, will need to add a listener on the Master ELB.

The decision was made not to create this ELB listener to keep the cluster "secure by default" but we will revisit this in the next release.
