### ISSUE TITLE
Request to create a fixed entry to Ansible server

### ISSUE THREAD

**Issue by philipho11** [aws-quickstart/quickstart-redhat-openshift#94]
Is there any easy way to create a fixed entry point to bastion/ansible server?

Now every time the stack is re-created, the Bastion host target changed and so is the ssh target from local workstation.

Sorry if this is out of scope of this project. But I think it would tremendously help anyone who always recreating the stack by running this CF template.

Philip

**Comment by jaymccon** [comment]
Hi @philipho11,

You could manually create an EIP and then assign it to the bastion host, then when stack is deleted and re-created just re-attach the eni.

You're correct that this doesn't quite fit into the scope of the quickstart, so it's unlikely we'll build something like this in, but you could easily do it manually, or fork and extend the template to provide an EIP parameter that automatically attaches your EIP.

**Comment by philipho11** [comment]
https://github.com/aws-quickstart/quickstart-redhat-openshift/blob/e9d750ea954131f51b2574f2c318936c44d34bd6/templates/openshift.template#L2911

To achieve this, this is the procedure?

1. to stop associating floating IP to ansible config host in line 2911. 
2. to allow user input EIP
3. to associate the EIP to ansible config host.

**Comment by agamzn** [comment]
@philipho11 Correct. Although in the case of a VPC, the user would need to input the EIP Association ID. 

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/quickref-ec2.html#scenario-ec2-eip-association-vpc
