### ISSUE TITLE
[ Question ] Does the QS Team has any plans to add upgrade features ?

### ISSUE THREAD

**Issue by philipakash** [aws-quickstart/quickstart-redhat-openshift#96]
Is there a plan in coming releases to tackle graceful Openshift upgrades in conjunction with the Automatic In Place Upgrades .
Ref: https://docs.openshift.com/container-platform/3.7/upgrading/automated_upgrades.html

Right now we change the repos and rebuild the cluster but  just wanted to know if moving forward do you have plan to change the strategy on how we upgrade/downgrade Open Shift clusters through Userdata?

**Comment by jaymccon** [comment]
@philipakash there are no immediate plans to add automated upgrades at this point, that said users should be able to upgrade a cluster launched by the QuickStart by following the steps [here](https://docs.openshift.com/container-platform/3.7/upgrading/automated_upgrades.html#running-the-upgrade-playbook-directly). 

We will be adding support for 3.9 shortly after it goes GA, and will revisit this request when that work is in progress.

**Comment by pierreozoux** [comment]
I saw you updated to 3.9 . Was it smotth upgrade?
I plan on using this in our org, and of course, upgrade are necessary :)
