### ISSUE TITLE
Create fails due to AnsibleConfigServer (unquoted parameter)

### ISSUE THREAD

**Issue by johnweldon** [aws-quickstart/quickstart-redhat-openshift#98]
When standing up the AnsibleConfigServer, the stack was failing and rolling back due to AnsibleConfigServer failing.

Looking at the logs I found that the Red Hat username and password are being passed as parameters to a shell script (redhat_ose-register.sh), unquoted.  In my case the password had an `&` in it which was not quoted so the shell interpreted that as a 'background this process cue'

I've opened #97 as a possible fix, although maybe the username needs to be quoted too.

(This appears to be a different issue than #90)

**Comment by jaymccon** [comment]
addressed by PR #97
