### ISSUE TITLE
Are security groups setup/mapped correctly?

### ISSUE THREAD

**Issue by dudash** [aws-quickstart/quickstart-redhat-openshift#99]
I'm looking at the security groups configured in templates/openshift.template.  I just wanted to check that this isn't an issue because it seems a little odd based on the SG descriptions.  

A few thoughts:
* should the internal port 22 access (in private subnets) be restricted to coming from the ansible config server?
* should the the launch configs use a different security group than the ELBs?
* should the ansible config server have it's own security group?  especially since it's in the public subnet? 

I get that the NAT Gateway and private subnet route table keeps the outside out.  But I wanted to ask to make sure there weren't any cut/paste errors and that things map the way they were intended to.

This is the current mapping.

**OpenShiftSecurityGroup** - Allow console access to the master instances
ALL PROTOCOLS ALL PORTS FOR VPC
443,22 FOR [RemoteAccessCIDR]
Used by: _OpenShiftEtcdLaunchConfig, OpenShiftNodesLaunchConfig, OpenShiftMasterASLaunchConfig, OpenShiftMasterELB, OpenShiftNodeInternalELB, AnsibleConfigServer_

**OpenShiftNodeSecurityGroup** - Allow access to the Workload instances
ALL PROTOCOLS ALL PORTS FOR VPC
443,80 for [ContainerAccessCIDR]
Used by: _ContainerAccessELB_

**OpenShiftInternalSecurityGroup** - Allow access to the Workload instances
ALL PROTOCOLS ALL PORTS FOR ANYONE
Used by: _OpenShiftMasterInternalELB_

**Comment by jaymccon** [comment]
@dudash Thanks for raising this

While the actual configuration of the groups seems sensible to me at first glance, the descriptions and names are confusing, I will review the rules and naming more thoroughly and update.
